import {decompressAST} from "../../shader/glsl";
const data = {
    "name": "view",
    "code": "#pragma export\r\nlayout(set = 0, binding = VIEW_BINDING) uniform ViewUniforms {\r\n  mat4 projectionMatrix;\r\n  mat4 viewMatrix;\r\n  vec4 viewPosition;\r\n  vec2 viewResolution;\r\n  vec2 viewSize;\r\n} viewUniforms;\r\n\r\n#pragma export\r\nvec4 worldToView(vec4 position) {\r\n  return viewUniforms.viewMatrix * position;\r\n}\r\n\r\n#pragma export\r\nvec4 viewToClip(vec4 position) {\r\n  return viewUniforms.projectionMatrix * position;\r\n}\r\n\r\n#pragma export\r\nvec4 worldToClip(vec4 position) {\r\n  return viewToClip(worldToView(position));\r\n}\r\n\r\n#pragma export\r\nvec3 clipToScreen3D(vec4 position) {\r\n  return vec3(position.xy * viewUniforms.viewSize, position.z);\r\n}\r\n\r\n#pragma export\r\nvec3 screenToClip3D(vec4 position) {\r\n  return vec3(position.xy * viewUniforms.viewResolution, position.z);\r\n}\r\n\r\n#pragma export\r\nvec3 worldToClip3D(vec4 position) {\r\n  position = viewToClip(worldToView(position));\r\n  return position.xyz / position.w;\r\n}\r\n",
    "table": {"hash":"o748dvzthr","symbols":["worldToView","viewToClip","worldToClip","clipToScreen3D","screenToClip3D","worldToClip3D","viewUniforms","ViewUniforms"],"visibles":["worldToView","viewToClip","worldToClip","clipToScreen3D","screenToClip3D","worldToClip3D","viewUniforms","ViewUniforms"],"globals":[],"externals":[],"modules":[],"functions":[{"at":225,"symbols":["worldToView"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"worldToView","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":327,"symbols":["viewToClip"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"viewToClip","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":434,"symbols":["worldToClip"],"identifiers":["viewToClip","worldToView"],"flags":1,"prototype":{"name":"worldToClip","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":535,"symbols":["clipToScreen3D"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"clipToScreen3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}},{"at":659,"symbols":["screenToClip3D"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"screenToClip3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}},{"at":789,"symbols":["worldToClip3D"],"identifiers":["viewToClip","worldToView"],"flags":1,"prototype":{"name":"worldToClip3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}}],"declarations":[{"at":16,"symbols":["viewUniforms","ViewUniforms"],"identifiers":[],"flags":1,"struct":{"name":"viewUniforms","type":{"name":"ViewUniforms","qualifiers":["layout(set = 0, binding = VIEW_BINDING)","uniform"]},"struct":{"members":[{"name":"projectionMatrix","type":{"name":"mat4"}},{"name":"viewMatrix","type":{"name":"mat4"}},{"name":"viewPosition","type":{"name":"vec4"}},{"name":"viewResolution","type":{"name":"vec2"}},{"name":"viewSize","type":{"name":"vec2"}}]}}}]},
    "shake": [[16,["viewUniforms","worldToView","worldToClip","worldToClip3D","viewToClip","clipToScreen3D","screenToClip3D","ViewUniforms"]],[225,["worldToView","worldToClip","worldToClip3D"]],[327,["viewToClip","worldToClip","worldToClip3D"]],[434,["worldToClip"]],[535,["clipToScreen3D"]],[659,["screenToClip3D"]],[789,["worldToClip3D"]]],
    "tree": decompressAST([["Skip",0,15],["Shake",16,205],["Id",23,26],["Id",32,39],["Id",42,54],["Id",64,76],["Id",87,103],["Id",113,123],["Id",133,145],["Id",155,169],["Id",179,187],["Id",192,204],["Skip",209,224],["Shake",225,307],["Id",230,241],["Id",247,255],["Id",269,281],["Id",295,303],["Skip",311,326],["Shake",327,414],["Id",332,342],["Id",348,356],["Id",370,382],["Id",402,410],["Skip",418,433],["Shake",434,515],["Id",439,450],["Id",456,464],["Id",478,488],["Id",489,500],["Id",501,509],["Skip",519,534],["Shake",535,639],["Id",540,554],["Id",560,568],["Id",587,595],["Id",601,613],["Id",624,632],["Skip",643,658],["Shake",659,769],["Id",664,678],["Id",684,692],["Id",711,719],["Id",725,737],["Id",754,762],["Skip",773,788],["Shake",789,913],["Id",794,807],["Id",813,821],["Id",828,836],["Id",839,849],["Id",850,861],["Id",862,870],["Id",884,892],["Id",899,907]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const worldToView = getSymbol("worldToView");
export const viewToClip = getSymbol("viewToClip");
export const worldToClip = getSymbol("worldToClip");
export const clipToScreen3D = getSymbol("clipToScreen3D");
export const screenToClip3D = getSymbol("screenToClip3D");
export const worldToClip3D = getSymbol("worldToClip3D");
export const viewUniforms = getSymbol("viewUniforms");
export const ViewUniforms = getSymbol("ViewUniforms");
/* __GLSL_LOADER_GENERATED */