import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/glsl";
const data = {
    "name": "view",
    "code": "#pragma export\r\nlayout(set = VIEW_BINDGROUP, binding = VIEW_BINDING) uniform ViewUniforms {\r\n  mat4 projectionMatrix;\r\n  mat4 viewMatrix;\r\n  vec4 viewPosition;\r\n  vec2 viewResolution;\r\n  vec2 viewSize;\r\n  float viewWorldUnit;\r\n  float viewPixelRatio;\r\n} viewUniforms;\r\n\r\n#pragma export\r\nvec4 worldToView(vec4 position) {\r\n  return viewUniforms.viewMatrix * position;\r\n}\r\n\r\n#pragma export\r\nvec4 viewToClip(vec4 position) {\r\n  return viewUniforms.projectionMatrix * position;\r\n}\r\n\r\n#pragma export\r\nvec4 worldToClip(vec4 position) {\r\n  return viewToClip(worldToView(position));\r\n}\r\n\r\n#pragma export\r\nvec3 clipToScreen3D(vec4 position) {\r\n  return vec3(position.xy * viewUniforms.viewSize, position.z);\r\n}\r\n\r\n#pragma export\r\nvec3 screenToClip3D(vec4 position) {\r\n  return vec3(position.xy * viewUniforms.viewResolution, position.z);\r\n}\r\n\r\n#pragma export\r\nvec3 worldToClip3D(vec4 position) {\r\n  position = viewToClip(worldToView(position));\r\n  return position.xyz / position.w;\r\n}\r\n\r\n#pragma export\r\nfloat getPerspectiveScale(float w, float f) {\r\n  mat4 m = viewUniforms.projectionMatrix;\r\n  float worldScale = m[1][1] * viewUniforms.viewWorldUnit;\r\n  float clipScale = mix(1.0, worldScale / w, f);\r\n  float pixelScale = clipScale * viewUniforms.viewPixelRatio;\r\n  return pixelScale;\r\n}\r\n",
    "table": {"hash":"lrk02vsdh8","symbols":["worldToView","viewToClip","worldToClip","clipToScreen3D","screenToClip3D","worldToClip3D","getPerspectiveScale","viewUniforms","ViewUniforms"],"visibles":["worldToView","viewToClip","worldToClip","clipToScreen3D","screenToClip3D","worldToClip3D","getPerspectiveScale","viewUniforms","ViewUniforms"],"functions":[{"at":287,"symbols":["worldToView"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"worldToView","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":389,"symbols":["viewToClip"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"viewToClip","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":496,"symbols":["worldToClip"],"identifiers":["viewToClip","worldToView"],"flags":1,"prototype":{"name":"worldToClip","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4","position"]}},{"at":597,"symbols":["clipToScreen3D"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"clipToScreen3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}},{"at":721,"symbols":["screenToClip3D"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"screenToClip3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}},{"at":851,"symbols":["worldToClip3D"],"identifiers":["viewToClip","worldToView"],"flags":1,"prototype":{"name":"worldToClip3D","type":{"name":"vec3","qualifiers":[]},"parameters":["vec4","position"]}},{"at":995,"symbols":["getPerspectiveScale"],"identifiers":["viewUniforms"],"flags":1,"prototype":{"name":"getPerspectiveScale","type":{"name":"float","qualifiers":[]},"parameters":["float","w"]}}],"declarations":[{"at":16,"symbols":["viewUniforms","ViewUniforms"],"identifiers":[],"flags":1,"struct":{"name":"viewUniforms","type":{"name":"ViewUniforms","qualifiers":["layout(set = VIEW_BINDGROUP, binding = VIEW_BINDING)","uniform"]},"struct":{"members":[{"name":"projectionMatrix","type":{"name":"mat4"}},{"name":"viewMatrix","type":{"name":"mat4"}},{"name":"viewPosition","type":{"name":"vec4"}},{"name":"viewResolution","type":{"name":"vec2"}},{"name":"viewSize","type":{"name":"vec2"}},{"name":"viewWorldUnit","type":{"name":"float"}},{"name":"viewPixelRatio","type":{"name":"float"}}]}}}]},
    "shake": [[16,["viewUniforms","worldToView","worldToClip","worldToClip3D","viewToClip","clipToScreen3D","screenToClip3D","getPerspectiveScale","ViewUniforms"]],[287,["worldToView","worldToClip","worldToClip3D"]],[389,["viewToClip","worldToClip","worldToClip3D"]],[496,["worldToClip"]],[597,["clipToScreen3D"]],[721,["screenToClip3D"]],[851,["worldToClip3D"]],[995,["getPerspectiveScale"]]],
    "tree": decompressAST([["Skip",0,15],["Shake",16,267],["Id",23,26],["Id",29,43],["Id",45,52],["Id",55,67],["Id",77,89],["Id",100,116],["Id",126,136],["Id",146,158],["Id",168,182],["Id",192,200],["Id",211,224],["Id",235,249],["Id",254,266],["Skip",271,286],["Shake",287,369],["Id",292,303],["Id",309,317],["Id",331,343],["Id",357,365],["Skip",373,388],["Shake",389,476],["Id",394,404],["Id",410,418],["Id",432,444],["Id",464,472],["Skip",480,495],["Shake",496,577],["Id",501,512],["Id",518,526],["Id",540,550],["Id",551,562],["Id",563,571],["Skip",581,596],["Shake",597,701],["Id",602,616],["Id",622,630],["Id",649,657],["Id",663,675],["Id",686,694],["Skip",705,720],["Shake",721,831],["Id",726,740],["Id",746,754],["Id",773,781],["Id",787,799],["Id",816,824],["Skip",835,850],["Shake",851,975],["Id",856,869],["Id",875,883],["Id",890,898],["Id",901,911],["Id",912,923],["Id",924,932],["Id",946,954],["Id",961,969],["Skip",979,994],["Shake",995,1281],["Id",1001,1020],["Id",1027,1028],["Id",1036,1037],["Id",1049,1050],["Id",1053,1065],["Id",1093,1103],["Id",1106,1107],["Id",1116,1128],["Id",1153,1162],["Id",1165,1168],["Id",1174,1184],["Id",1187,1188],["Id",1190,1191],["Id",1203,1213],["Id",1216,1225],["Id",1228,1240],["Id",1267,1277]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const worldToView = getSymbol("worldToView");
export const viewToClip = getSymbol("viewToClip");
export const worldToClip = getSymbol("worldToClip");
export const clipToScreen3D = getSymbol("clipToScreen3D");
export const screenToClip3D = getSymbol("screenToClip3D");
export const worldToClip3D = getSymbol("worldToClip3D");
export const getPerspectiveScale = getSymbol("getPerspectiveScale");
export const viewUniforms = getSymbol("viewUniforms");
export const ViewUniforms = getSymbol("ViewUniforms");
/* __GLSL_LOADER_GENERATED */