import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/glsl";
import m0 from "../../../gen-glsl/use/types";
import m1 from "../../../gen-glsl/use/view";
import m2 from "../../../gen-glsl/geometry/quad";
const data = {
    "name": "quad",
    "code": "#pragma import {SolidVertex} from '../../../glsl/use/types'\r\n#pragma import {viewUniforms, worldToClip, getPerspectiveScale} from '../../../glsl/use/view'\r\n#pragma import {getQuadUV} from '../../../glsl/geometry/quad'\r\n\r\nvec4 getPosition(int);\r\nvec4 getColor(int);\r\nvec2 getSize(int);\r\nfloat getDepth(int);\r\n\r\n#pragma export\r\nSolidVertex getQuadVertex(int vertexIndex, int instanceIndex) {\r\n  vec4 position = getPosition(instanceIndex);\r\n  vec4 color = getColor(instanceIndex);\r\n  vec2 size = getSize(instanceIndex);\r\n  float depth = getDepth(instanceIndex);\r\n\r\n  vec4 center = worldToClip(position);\r\n\r\n  vec2 uv = getQuadUV(vertexIndex);\r\n  vec2 xy = uv * 2.0 - 1.0;\r\n  \r\n  // Lerp between fixed size and full perspective.\r\n  float pixelScale = getPerspectiveScale(center.w, depth);\r\n  size *= pixelScale;\r\n\r\n  #ifdef HAS_EDGE_BLEED\r\n  xy = xy * (size + 0.5) / size;\r\n  uv = xy * .5 + .5;\r\n  #endif\r\n\r\n  center.xy += xy * size * viewUniforms.viewResolution * center.w;\r\n\r\n  return SolidVertex(\r\n    center,\r\n    color,\r\n    uv\r\n  );\r\n}",
    "table": {"hash":"7szhdhjmn5","symbols":["getQuadVertex","getPosition","getColor","getSize","getDepth"],"visibles":["getQuadVertex"],"externals":[{"at":221,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":245,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":266,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"vec2","qualifiers":[]},"parameters":["int"]}},{"at":286,"symbols":["getDepth"],"identifiers":[],"flags":0,"prototype":{"name":"getDepth","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}],"modules":[{"at":0,"name":"../../../glsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]},{"at":0,"name":"../../../glsl/use/view","symbols":["viewUniforms","worldToClip","getPerspectiveScale"],"imports":[{"name":"viewUniforms","imported":"viewUniforms"},{"name":"worldToClip","imported":"worldToClip"},{"name":"getPerspectiveScale","imported":"getPerspectiveScale"}]},{"at":0,"name":"../../../glsl/geometry/quad","symbols":["getQuadUV"],"imports":[{"name":"getQuadUV","imported":"getQuadUV"}]}],"functions":[{"at":326,"symbols":["getQuadVertex"],"identifiers":["getPosition","getColor","getSize","getDepth"],"flags":1,"prototype":{"name":"getQuadVertex","type":{"name":"SolidVertex","qualifiers":[]},"parameters":["int","vertexIndex"]}}],"declarations":[{"at":221,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":245,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":266,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"vec2","qualifiers":[]},"parameters":["int"]}},{"at":286,"symbols":["getDepth"],"identifiers":[],"flags":0,"prototype":{"name":"getDepth","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}]},
    "shake": [[221,["getPosition","getQuadVertex"]],[245,["getColor","getQuadVertex"]],[266,["getSize","getQuadVertex"]],[286,["getDepth","getQuadVertex"]],[326,["getQuadVertex"]]],
    "tree": decompressAST([["Skip",0,60],["Skip",61,155],["Skip",156,218],["Shake",221,243],["Id",226,237],["Shake",245,264],["Id",250,258],["Shake",266,284],["Id",271,278],["Shake",286,306],["Id",292,300],["Skip",310,325],["Shake",326,1037],["Id",326,337],["Id",338,351],["Id",356,367],["Id",373,386],["Id",398,406],["Id",409,420],["Id",421,434],["Id",445,450],["Id",453,461],["Id",462,475],["Id",486,490],["Id",493,500],["Id",501,514],["Id",526,531],["Id",534,542],["Id",543,556],["Id",569,575],["Id",578,589],["Id",590,598],["Id",611,613],["Id",616,625],["Id",626,637],["Id",648,650],["Id",653,655],["Id",734,744],["Id",747,766],["Id",767,773],["Id",777,782],["Id",788,792],["Id",796,806],["Id",838,840],["Id",843,845],["Id",849,853],["Id",863,867],["Id",872,874],["Id",877,879],["Id",906,912],["Id",919,921],["Id",924,928],["Id",931,943],["Id",961,967],["Id",983,994],["Id",1001,1007],["Id",1014,1019],["Id",1026,1028]]),
  };
const libs = {"../../../glsl/use/types": m0, "../../../glsl/use/view": m1, "../../../glsl/geometry/quad": m2};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getQuadVertex = getSymbol("getQuadVertex");
/* __GLSL_LOADER_GENERATED */