import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
const data = {
    "name": "solid",
    "code": "@optional @link fn getFragment(color: vec4<f32>, uv: vec4<f32>, st: vec4<f32>) -> vec4<f32> { return color; }\r\n\r\n@fragment\r\nfn main(\r\n  @location(0) fragColor: vec4<f32>,\r\n  @location(1) fragUV: vec4<f32>,  \r\n  @location(2) fragST: vec4<f32>,  \r\n) -> @location(0) vec4<f32> {\r\n  var outColor = fragColor;\r\n\r\n  outColor = getFragment(outColor, fragUV, fragST);\r\n  if (outColor.a <= 0.0) { discard; }\r\n\r\n  return outColor;\r\n}\r\n",
    "hash": 5817745002914903,
    "table": {"symbols":["getFragment","main"],"visibles":["main"],"externals":[{"at":0,"symbol":"getFragment","flags":6,"func":{"name":"getFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"st","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}}],"exports":[{"at":113,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"vec4","args":[{"name":"f32"}],"attributes":[{"name":"location","args":["0"]}]},"attributes":[{"name":"fragment"}],"parameters":[{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"fragST","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]}],"identifiers":["getFragment"]}}],"declarations":[{"at":0,"symbol":"getFragment","flags":6,"func":{"name":"getFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"st","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":113,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"vec4","args":[{"name":"f32"}],"attributes":[{"name":"location","args":["0"]}]},"attributes":[{"name":"fragment"}],"parameters":[{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"fragST","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]}],"identifiers":["getFragment"]}}]},
    "shake": [[0,["getFragment","main"]],[113,["main"]]],
    "tree": decompressAST([["Opt",0,109,"getFragment"],["Skip",0,9],["Skip",10,15],["Id",19,30],["Id",31,36],["Id",49,51],["Id",64,66],["Id",101,106],["Shake",113,423],["Attr",113,122],["Id",114,122],["Id",127,131],["Attr",136,148],["Id",137,145],["Id",149,158],["Attr",174,186],["Id",175,183],["Id",187,193],["Attr",211,223],["Id",212,220],["Id",224,230],["Attr",251,263],["Id",252,260],["Id",283,291],["Id",294,303],["Id",310,318],["Id",321,332],["Id",333,341],["Id",343,349],["Id",351,357],["Id",367,375],["Id",376,377],["Id",411,419]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const main = getSymbol("main");
/* __WGSL_LOADER_GENERATED */