// File generated by build.mjs. Do not edit directly.
import _fragmentpbr from "./fragment/pbr.glsl";
import _geometryquad from "./geometry/quad.glsl";
import _instancequadfragment from "./instance/quad/fragment.glsl";
import _instancequadvertex from "./instance/quad/vertex.glsl";
import _usetypes from "./use/types.glsl";
import _useview from "./use/view.glsl";
const Modules = {
 "fragment/pbr": _fragmentpbr,
 "geometry/quad": _geometryquad,
 "instance/quad/fragment": _instancequadfragment,
 "instance/quad/vertex": _instancequadvertex,
 "use/types": _usetypes,
 "use/view": _useview,
} as Record<string, string>;
export default Modules;
