import { decompressAST } from "../../../shader/transform/ast";
import * as m0 from "../../../../../glsl/fragment/pbr";
import * as m1 from "../../../../../glsl/use/picking";
import * as m2 from "../../../../../glsl/use/view";
import * as m3 from "../../../../../glsl/use/light";
const data = {
  "name": "mesh",
  "code": "#pragma import {PBR} from '../../../glsl/fragment/pbr';\r\n#pragma import {getPickingColor} from '../../../glsl/use/picking';\r\n#pragma import {viewUniforms} from '../../../glsl/use/view';\r\n#pragma import {lightUniforms} from '../../../glsl/use/light';\r\n\r\n#ifdef IS_PICKING\r\nlayout(location = 0) in flat uint fragIndex;\r\nlayout(location = 0) out uvec4 outColor;\r\n#else\r\nlayout(location = 0) in vec4 fragColor;\r\nlayout(location = 1) in vec2 fragUV;\r\n\r\nlayout(location = 2) in vec3 fragNormal;\r\nlayout(location = 3) in vec3 fragPosition;\r\n\r\nlayout(location = 0) out vec4 outColor;\r\n#endif\r\n\r\n#ifdef IS_PICKING\r\nvoid main() {\r\n  outColor = getPickingColor(fragIndex);\r\n}\r\n#else\r\nvoid main() {\r\n  vec3 fragLight = lightUniforms.lightPosition.xyz - fragPosition;\r\n  vec3 fragView = viewUniforms.viewPosition.xyz - fragPosition;\r\n\r\n  vec3 N = normalize(fragNormal);\r\n  vec3 L = normalize(fragLight);\r\n  vec3 V = normalize(fragView);\r\n\r\n  vec3 albedo = fragColor.rgb;\r\n  float metalness = 0.2;\r\n  float roughness = 0.8;\r\n\r\n  vec3 color = PBR(N, L, V, albedo, metalness, roughness) * lightUniforms.lightColor.xyz;\r\n  outColor = vec4(color, fragColor.a);\r\n}\r\n#endif\r\n\r\n",
  "table": {"hash":"8sgv5fsexn","symbols":["main","fragIndex","outColor","fragColor","fragUV","fragNormal","fragPosition"],"visibles":[],"globals":[],"externals":[],"modules":[{"at":0,"name":"../../../glsl/fragment/pbr","symbols":["PBR"],"imports":[{"name":"PBR","imported":"PBR"}]},{"at":0,"name":"../../../glsl/use/picking","symbols":["getPickingColor"],"imports":[{"name":"getPickingColor","imported":"getPickingColor"}]},{"at":0,"name":"../../../glsl/use/view","symbols":["viewUniforms"],"imports":[{"name":"viewUniforms","imported":"viewUniforms"}]},{"at":0,"name":"../../../glsl/use/light","symbols":["lightUniforms"],"imports":[{"name":"lightUniforms","imported":"lightUniforms"}]}],"functions":[{"at":606,"symbols":["main"],"identifiers":["outColor","fragIndex"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}},{"at":673,"symbols":["main"],"identifiers":["fragPosition","fragNormal","fragColor","outColor"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}}],"declarations":[{"at":272,"symbols":["fragIndex"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uint","qualifiers":["layout(location = 0)","in","flat"]},"locals":[{"name":"fragIndex","expr":null}]}},{"at":318,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uvec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}},{"at":367,"symbols":["fragColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","in"]},"locals":[{"name":"fragColor","expr":null}]}},{"at":408,"symbols":["fragUV"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 1)","in"]},"locals":[{"name":"fragUV","expr":null}]}},{"at":448,"symbols":["fragNormal"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec3","qualifiers":["layout(location = 2)","in"]},"locals":[{"name":"fragNormal","expr":null}]}},{"at":490,"symbols":["fragPosition"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec3","qualifiers":["layout(location = 3)","in"]},"locals":[{"name":"fragPosition","expr":null}]}},{"at":536,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}}]},
  "shake": [[272,["fragIndex","main"]],[318,["outColor","main"]],[367,["fragColor","main"]],[408,["fragUV"]],[448,["fragNormal","main"]],[490,["fragPosition","main"]],[536,["outColor","main"]],[606,["main"]],[673,["main"]]],
  "tree": decompressAST([["Skip",0,56],["Skip",57,124],["Skip",125,186],["Skip",187,250],["Shake",272,316],["Id",279,287],["Id",306,315],["Shake",318,358],["Id",325,333],["Id",349,357],["Shake",367,406],["Id",374,382],["Id",396,405],["Shake",408,444],["Id",415,423],["Id",437,443],["Shake",448,488],["Id",455,463],["Id",477,487],["Shake",490,532],["Id",497,505],["Id",519,531],["Shake",536,575],["Id",543,551],["Id",566,574],["Shake",606,664],["Id",611,615],["Id",623,631],["Id",634,649],["Id",650,659],["Shake",673,1145],["Id",678,682],["Id",695,704],["Id",707,720],["Id",741,753],["Id",763,771],["Id",774,786],["Id",806,818],["Id",830,831],["Id",834,843],["Id",844,854],["Id",865,866],["Id",869,878],["Id",879,888],["Id",899,900],["Id",903,912],["Id",913,921],["Id",934,940],["Id",943,952],["Id",967,976],["Id",993,1002],["Id",1020,1025],["Id",1028,1031],["Id",1032,1033],["Id",1035,1036],["Id",1038,1039],["Id",1041,1047],["Id",1049,1058],["Id",1060,1069],["Id",1073,1086],["Id",1106,1114],["Id",1122,1127],["Id",1129,1138]])
};
const libs = { "../../../glsl/fragment/pbr": m0, "../../../glsl/use/picking": m1, "../../../glsl/use/view": m2, "../../../glsl/use/light": m3 };
const getSymbol = (entry?: string) => ({ module: data, libs, entry });
export default getSymbol();
