import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/glsl";
import m0 from "../../../gen-glsl/use/picking";
const data = {
    "name": "solid",
    "code": "#pragma import {getPickingColor} from '../../../glsl/use/picking';\r\n\r\nvec4 getFragment(vec4, vec2);\r\n\r\n#ifdef IS_PICKING\r\nlayout(location = 0) in flat uint fragIndex;\r\nlayout(location = 0) out uvec4 outColor;\r\n#else\r\nlayout(location = 0) in vec4 fragColor;\r\nlayout(location = 1) in vec2 fragUV;\r\n\r\nlayout(location = 0) out vec4 outColor;\r\n#endif\r\n\r\n#ifdef IS_PICKING\r\nvoid main() {\r\n  outColor = getPickingColor(fragIndex);\r\n}\r\n#else\r\nvoid main() {\r\n  outColor = fragColor;\r\n  outColor.xyz *= outColor.a;\r\n\r\n  outColor = getFragment(outColor, fragUV);\r\n\r\n  if (outColor.a <= 0.0) discard;\r\n}\r\n#endif\r\n",
    "table": {"hash":"5kphnw3j5i","symbols":["main","getFragment","fragIndex","outColor","fragColor","fragUV"],"externals":[{"at":70,"symbols":["getFragment"],"identifiers":[],"flags":0,"prototype":{"name":"getFragment","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4"]}}],"modules":[{"at":0,"name":"../../../glsl/use/picking","symbols":["getPickingColor"],"imports":[{"name":"getPickingColor","imported":"getPickingColor"}]}],"functions":[{"at":368,"symbols":["main"],"identifiers":["outColor","fragIndex"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}},{"at":435,"symbols":["main"],"identifiers":["outColor","fragColor","getFragment","fragUV"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}}],"declarations":[{"at":70,"symbols":["getFragment"],"identifiers":[],"flags":0,"prototype":{"name":"getFragment","type":{"name":"vec4","qualifiers":[]},"parameters":["vec4"]}},{"at":122,"symbols":["fragIndex"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uint","qualifiers":["layout(location = 0)","in","flat"]},"locals":[{"name":"fragIndex","expr":null}]}},{"at":168,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uvec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}},{"at":217,"symbols":["fragColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","in"]},"locals":[{"name":"fragColor","expr":null}]}},{"at":258,"symbols":["fragUV"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 1)","in"]},"locals":[{"name":"fragUV","expr":null}]}},{"at":298,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}}]},
    "shake": [[70,["getFragment","main"]],[122,["fragIndex","main"]],[168,["outColor","main"]],[217,["fragColor","main"]],[258,["fragUV","main"]],[298,["outColor","main"]],[368,["main"]],[435,["main"]]],
    "tree": decompressAST([["Skip",0,67],["Shake",70,99],["Id",75,86],["Shake",122,166],["Id",129,137],["Id",156,165],["Shake",168,208],["Id",175,183],["Id",199,207],["Shake",217,256],["Id",224,232],["Id",246,255],["Shake",258,294],["Id",265,273],["Id",287,293],["Shake",298,337],["Id",305,313],["Id",328,336],["Shake",368,426],["Id",373,377],["Id",385,393],["Id",396,411],["Id",412,421],["Shake",435,591],["Id",440,444],["Id",452,460],["Id",463,472],["Id",477,485],["Id",493,501],["Id",510,518],["Id",521,532],["Id",533,541],["Id",543,549],["Id",561,569]]),
  };
const libs = {"../../../glsl/use/picking": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __GLSL_LOADER_GENERATED */