import {decompressAST} from "../../../shader/glsl";
import m0 from "../../../gen-glsl/use/picking";
const data = {
    "name": "solid",
    "code": "#pragma import {getPickingColor} from '../../../glsl/use/picking';\r\n\r\n#ifdef HAS_MASK\r\n#pragma optional\r\nfloat getMask(vec2);\r\n#endif\r\n\r\n#ifdef HAS_TEXTURE\r\n#pragma optional\r\nvec4 getTexture(vec2);\r\n#endif\r\n\r\n#ifdef IS_PICKING\r\nlayout(location = 0) in flat uint fragIndex;\r\nlayout(location = 0) out uvec4 outColor;\r\n#else\r\nlayout(location = 0) in vec4 fragColor;\r\nlayout(location = 1) in vec2 fragUV;\r\n\r\nlayout(location = 0) out vec4 outColor;\r\n#endif\r\n\r\n#ifdef IS_PICKING\r\nvoid main() {\r\n  outColor = getPickingColor(fragIndex);\r\n}\r\n#else\r\nvoid main() {\r\n  outColor = fragColor;\r\n\r\n  #ifdef HAS_MASK\r\n  outColor *= getMask(fragUV);\r\n  #endif\r\n  #ifdef HAS_TEXTURE\r\n  outColor *= getTexture(fragUV);\r\n  #endif\r\n\r\n  if (outColor.a <= 0.0) discard;\r\n}\r\n#endif\r\n",
    "table": {"hash":"pmu5p1qwj3","symbols":["main","getMask","getTexture","fragIndex","outColor","fragColor","fragUV"],"visibles":[],"globals":[],"externals":[{"at":105,"symbols":["getMask"],"identifiers":[],"flags":2,"prototype":{"name":"getMask","type":{"name":"float","qualifiers":[]},"parameters":["vec2"]}},{"at":175,"symbols":["getTexture"],"identifiers":[],"flags":2,"prototype":{"name":"getTexture","type":{"name":"vec4","qualifiers":[]},"parameters":["vec2"]}}],"modules":[{"at":0,"name":"../../../glsl/use/picking","symbols":["getPickingColor"],"imports":[{"name":"getPickingColor","imported":"getPickingColor"}]}],"functions":[{"at":474,"symbols":["main"],"identifiers":["outColor","fragIndex"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}},{"at":541,"symbols":["main"],"identifiers":["outColor","fragColor","getMask","fragUV","getTexture"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}}],"declarations":[{"at":105,"symbols":["getMask"],"identifiers":[],"flags":2,"prototype":{"name":"getMask","type":{"name":"float","qualifiers":[]},"parameters":["vec2"]}},{"at":175,"symbols":["getTexture"],"identifiers":[],"flags":2,"prototype":{"name":"getTexture","type":{"name":"vec4","qualifiers":[]},"parameters":["vec2"]}},{"at":228,"symbols":["fragIndex"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uint","qualifiers":["layout(location = 0)","in","flat"]},"locals":[{"name":"fragIndex","expr":null}]}},{"at":274,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uvec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}},{"at":323,"symbols":["fragColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","in"]},"locals":[{"name":"fragColor","expr":null}]}},{"at":364,"symbols":["fragUV"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 1)","in"]},"locals":[{"name":"fragUV","expr":null}]}},{"at":404,"symbols":["outColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"outColor","expr":null}]}}]},
    "shake": [[105,["getMask","main"]],[175,["getTexture","main"]],[228,["fragIndex","main"]],[274,["outColor","main"]],[323,["fragColor","main"]],[364,["fragUV","main"]],[404,["outColor","main"]],[474,["main"]],[541,["main"]]],
    "tree": decompressAST([["Skip",0,67],["Skip",87,104],["Shake",105,125],["Id",111,118],["Skip",157,174],["Shake",175,197],["Id",180,190],["Shake",228,272],["Id",235,243],["Id",262,271],["Shake",274,314],["Id",281,289],["Id",305,313],["Shake",323,362],["Id",330,338],["Id",352,361],["Shake",364,400],["Id",371,379],["Id",393,399],["Shake",404,443],["Id",411,419],["Id",434,442],["Shake",474,532],["Id",479,483],["Id",491,499],["Id",502,517],["Id",518,527],["Shake",541,749],["Id",546,550],["Id",558,566],["Id",569,578],["Id",604,612],["Id",616,623],["Id",624,630],["Id",668,676],["Id",680,690],["Id",691,697],["Id",719,727]]),
  };
const libs = {"../../../glsl/use/picking": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __GLSL_LOADER_GENERATED */