import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wlsl";
import m0 from "../../../gen-wgsl/use/types";
const data = {
    "name": "virtual",
    "code": "use '../../../wgsl/use/types'::{ SolidVertex };\r\n\r\n@external fn getVertex(v: i32, i: i32) -> SolidVertex {};\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>;\r\n  @location(0) fragColor: vec4<f32>;\r\n  @location(1) fragUV: vec2<f32>;\r\n};\r\n\r\n@stage(vertex)\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  var v = getVertex(i32(vertexIndex), i32(instanceIndex));\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    v.color,\r\n    v.uv,\r\n  );\r\n}\r\n",
    "table": {"hash":"yoc95roavl","symbols":["getVertex","VertexOutput","main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]}],"declarations":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"i32"}},{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":108,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]}]}},{"at":257,"symbol":"main","flags":0,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"stage","args":["vertex"]}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput"]}}],"externals":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"i32"}},{"name":"i","type":{"name":"i32"}}],"identifiers":[]}}]},
    "shake": [[51,["getVertex","main"]],[108,["VertexOutput","main"]],[257,["main"]]],
    "tree": decompressAST([["Skip",0,46],["Skip",51,107],["Shake",108,252],["Id",119,131],["Attr",137,155],["Id",138,145],["Id",146,154],["Id",156,164],["Attr",180,192],["Id",181,189],["Id",193,202],["Attr",218,230],["Id",219,227],["Id",231,237],["Shake",257,531],["Attr",257,271],["Id",258,263],["Id",264,270],["Id",276,280],["Attr",285,307],["Id",286,293],["Id",294,306],["Id",308,319],["Attr",329,353],["Id",330,337],["Id",338,352],["Id",354,367],["Id",380,392],["Id",402,403],["Id",406,415],["Id",420,431],["Id",438,451],["Id",467,479],["Id",486,487],["Id",488,496],["Id",503,504],["Id",505,510],["Id",517,518],["Id",519,521]]),
  };
const libs = {"../../../wgsl/use/types": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __WGSL_LOADER_GENERATED */