import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wlsl";
import m0 from "../../../gen-wgsl/use/types";
const data = {
    "name": "virtual-pick",
    "code": "use '../../../wgsl/use/types'::{ SolidVertex };\r\n\r\n@external fn getVertex(v: i32, i: i32) -> SolidVertex {};\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>;\r\n  @location(0) @interpolate(flat) fragIndex: u32;\r\n};\r\n\r\n@stage(vertex)\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  var v = getVertex(i32(vertexIndex), i32(instanceIndex));\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    instanceIndex,\r\n  );\r\n}\r\n",
    "table": {"hash":"zka430bxuw","symbols":["getVertex","VertexOutput","main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]}],"declarations":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"i32"}},{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":108,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragIndex","type":{"name":"u32"},"attributes":[{"name":"location","args":["0"]},{"name":"interpolate","args":["flat"]}]}]}},{"at":235,"symbol":"main","flags":0,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"stage","args":["vertex"]}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput"]}}],"externals":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"i32"}},{"name":"i","type":{"name":"i32"}}],"identifiers":[]}}]},
    "shake": [[51,["getVertex","main"]],[108,["VertexOutput","main"]],[235,["main"]]],
    "tree": decompressAST([["Skip",0,46],["Skip",51,107],["Shake",108,230],["Id",119,131],["Attr",137,155],["Id",138,145],["Id",146,154],["Id",156,164],["Attr",180,192],["Id",181,189],["Attr",193,211],["Id",194,205],["Id",206,210],["Id",212,221],["Shake",235,504],["Attr",235,249],["Id",236,241],["Id",242,248],["Id",254,258],["Attr",263,285],["Id",264,271],["Id",272,284],["Id",286,297],["Attr",307,331],["Id",308,315],["Id",316,330],["Id",332,345],["Id",358,370],["Id",380,381],["Id",384,393],["Id",398,409],["Id",416,429],["Id",445,457],["Id",464,465],["Id",466,474],["Id",481,494]]),
  };
const libs = {"../../../wgsl/use/types": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __WGSL_LOADER_GENERATED */