import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/view";
const data = {
    "name": "mesh-pick",
    "code": "use '../../../wgsl/use/view'::{ worldToClip };\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) @interpolate(flat) fragId: u32,\r\n  @location(1) @interpolate(flat) fragIndex: u32,\r\n};\r\n\r\n@vertex\r\nfn main(\r\n  @builtin(instance_index) instanceIndex: u32,\r\n  @location(0) position: vec4<f32>,\r\n  @location(1) normal: vec4<f32>,\r\n  @location(2) color: vec4<f32>,\r\n  @location(3) uv: vec2<f32>,\r\n) -> VertexOutput {\r\n  \r\n  var outPosition: vec4<f32> = worldToClip(position);\r\n  var fragIndex = u32(instanceIndex);\r\n  \r\n  return VertexOutput(\r\n    outPosition,\r\n    u32(PICKING_ID),\r\n    fragIndex,\r\n  );\r\n}\r\n",
    "hash": 6748612560103766,
    "table": {"symbols":["VertexOutput","main"],"visibles":["main"],"modules":[{"at":0,"name":"../../../wgsl/use/view","symbols":["worldToClip"],"imports":[{"name":"worldToClip","imported":"worldToClip"}]}],"exports":[{"at":221,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]},{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"normal","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["3"]}]}],"identifiers":["VertexOutput"]}}],"declarations":[{"at":46,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragId","type":{"name":"u32"},"attributes":[{"name":"location","args":["0"]},{"name":"interpolate","args":["flat"]}]},{"name":"fragIndex","type":{"name":"u32"},"attributes":[{"name":"location","args":["1"]},{"name":"interpolate","args":["flat"]}]}]}},{"at":221,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]},{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"normal","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["3"]}]}],"identifiers":["VertexOutput"]}}]},
    "shake": [[46,["VertexOutput","main"]],[221,["main"]]],
    "tree": decompressAST([["Skip",0,45],["Shake",46,216],["Id",57,69],["Attr",75,93],["Id",76,83],["Id",84,92],["Id",94,102],["Attr",118,130],["Id",119,127],["Attr",131,149],["Id",132,143],["Id",144,148],["Id",150,156],["Attr",166,178],["Id",167,175],["Attr",179,197],["Id",180,191],["Id",192,196],["Id",198,207],["Shake",221,635],["Attr",221,228],["Id",222,228],["Id",233,237],["Attr",242,266],["Id",243,250],["Id",251,265],["Id",267,280],["Attr",290,302],["Id",291,299],["Id",303,311],["Attr",327,339],["Id",328,336],["Id",340,346],["Attr",362,374],["Id",363,371],["Id",375,380],["Attr",396,408],["Id",397,405],["Id",409,411],["Id",430,442],["Id",456,467],["Id",481,492],["Id",493,501],["Id",511,520],["Id",527,540],["Id",557,569],["Id",576,587],["Id",598,608],["Id",616,625]]),
  };
const libs = {"../../../wgsl/use/view": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const main = getSymbol("main");
/* __WGSL_LOADER_GENERATED */