import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/view";
const data = {
    "name": "mesh",
    "code": "use '../../../wgsl/use/view'::{ worldToClip };\r\n\r\n@optional @link fn toColorSpace(c: vec4<f32>) -> vec4<f32> { return c; }\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) fragColor: vec4<f32>,\r\n  @location(1) fragUV: vec2<f32>,\r\n  @location(2) fragNormal: vec3<f32>,\r\n  @location(3) fragPosition: vec3<f32>,\r\n};\r\n\r\n@vertex\r\nfn main(\r\n  @builtin(instance_index) instanceIndex: u32,\r\n  @location(0) position: vec4<f32>,\r\n  @location(1) normal: vec4<f32>,\r\n  @location(2) color: vec4<f32>,\r\n  @location(3) uv: vec2<f32>,\r\n) -> VertexOutput {\r\n  \r\n  var outPosition: vec4<f32> = worldToClip(position);\r\n  \r\n  return VertexOutput(\r\n    outPosition,\r\n    toColorSpace(color),\r\n    uv,\r\n    normal.xyz,\r\n    position.xyz,\r\n  );\r\n}\r\n",
    "hash": 3797151315317498,
    "table": {"symbols":["toColorSpace","VertexOutput","main"],"visibles":["main"],"modules":[{"at":0,"name":"../../../wgsl/use/view","symbols":["worldToClip"],"imports":[{"name":"worldToClip","imported":"worldToClip"}]}],"externals":[{"at":50,"symbol":"toColorSpace","flags":6,"func":{"name":"toColorSpace","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"c","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}}],"exports":[{"at":351,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]},{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"normal","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["3"]}]}],"identifiers":["VertexOutput","toColorSpace"]}}],"declarations":[{"at":50,"symbol":"toColorSpace","flags":6,"func":{"name":"toColorSpace","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"c","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":122,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"fragNormal","type":{"name":"vec3","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]},{"name":"fragPosition","type":{"name":"vec3","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["3"]}]}]}},{"at":351,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]},{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"normal","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["3"]}]}],"identifiers":["VertexOutput","toColorSpace"]}}]},
    "shake": [[50,["toColorSpace","main"]],[122,["VertexOutput","main"]],[351,["main"]]],
    "tree": decompressAST([["Skip",0,45],["Opt",50,122,"toColorSpace"],["Skip",50,59],["Skip",60,65],["Id",69,81],["Id",82,83],["Id",118,119],["Shake",122,346],["Id",133,145],["Attr",151,169],["Id",152,159],["Id",160,168],["Id",170,178],["Attr",194,206],["Id",195,203],["Id",207,216],["Attr",232,244],["Id",233,241],["Id",245,251],["Attr",267,279],["Id",268,276],["Id",280,290],["Attr",306,318],["Id",307,315],["Id",319,331],["Shake",351,759],["Attr",351,358],["Id",352,358],["Id",363,367],["Attr",372,396],["Id",373,380],["Id",381,395],["Id",397,410],["Attr",420,432],["Id",421,429],["Id",433,441],["Attr",457,469],["Id",458,466],["Id",470,476],["Attr",492,504],["Id",493,501],["Id",505,510],["Attr",526,538],["Id",527,535],["Id",539,541],["Id",560,572],["Id",586,597],["Id",611,622],["Id",623,631],["Id",648,660],["Id",667,678],["Id",685,697],["Id",698,703],["Id",711,713],["Id",720,726],["Id",727,730],["Id",737,745],["Id",746,749]]),
  };
const libs = {"../../../wgsl/use/view": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const main = getSymbol("main");
/* __WGSL_LOADER_GENERATED */