import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/types";
import m1 from "../../../gen-wgsl/use/color";
const data = {
    "name": "virtual-solid",
    "code": "use '../../../wgsl/use/types'::{ SolidVertex };\r\nuse \"../../../wgsl/use/color\"::{ toColorSpace };\r\n\r\n@external fn getVertex(v: u32, i: u32) -> SolidVertex {};\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) fragColor: vec4<f32>,\r\n  @location(1) fragUV: vec2<f32>,\r\n};\r\n\r\n@stage(vertex)\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  let v = getVertex(vertexIndex, instanceIndex);\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    toColorSpace(v.color),\r\n    v.uv,\r\n  );\r\n}\r\n",
    "hash": "fj5o562e1u",
    "table": {"symbols":["getVertex","VertexOutput","main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]},{"at":0,"name":"../../../wgsl/use/color","symbols":["toColorSpace"],"imports":[{"name":"toColorSpace","imported":"toColorSpace"}]}],"declarations":[{"at":101,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":158,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]}]}},{"at":307,"symbol":"main","flags":0,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"stage","args":["vertex"]}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput"]}}],"externals":[{"at":101,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}]},
    "shake": [[101,["getVertex","main"]],[158,["VertexOutput","main"]],[307,["main"]]],
    "tree": decompressAST([["Skip",0,46],["Skip",49,96],["Skip",101,157],["Shake",158,302],["Id",169,181],["Attr",187,205],["Id",188,195],["Id",196,204],["Id",206,214],["Attr",230,242],["Id",231,239],["Id",243,252],["Attr",268,280],["Id",269,277],["Id",281,287],["Shake",307,585],["Attr",307,321],["Id",308,313],["Id",314,320],["Id",326,330],["Attr",335,357],["Id",336,343],["Id",344,356],["Id",358,369],["Attr",379,403],["Id",380,387],["Id",388,402],["Id",404,417],["Id",430,442],["Id",452,453],["Id",456,465],["Id",466,477],["Id",479,492],["Id",507,519],["Id",526,527],["Id",528,536],["Id",543,555],["Id",556,557],["Id",558,563],["Id",571,572],["Id",573,575]]),
  };
const libs = {"../../../wgsl/use/types": m0, "../../../wgsl/use/color": m1};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __WGSL_LOADER_GENERATED */