import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/types";
const data = {
    "name": "virtual-pick",
    "code": "use '../../../wgsl/use/types'::{ PickVertex };\r\n\r\n@link fn getVertex(v: u32, i: u32) -> PickVertex {};\r\n@optional @link fn getId() -> u32 { return 0u; };\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) @interpolate(flat) fragId: u32,\r\n  @location(1) @interpolate(flat) fragIndex: u32,\r\n};\r\n\r\n@vertex\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  var v = getVertex(vertexIndex, instanceIndex);\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    getId(),\r\n    v.index,\r\n  );\r\n}\r\n",
    "hash": 2378838756765895,
    "table": {"symbols":["getVertex","getId","VertexOutput","main"],"visibles":["main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["PickVertex"],"imports":[{"name":"PickVertex","imported":"PickVertex"}]}],"externals":[{"at":50,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"PickVertex"},"attributes":[{"name":"link"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":104,"symbol":"getId","flags":6,"func":{"name":"getId","type":{"name":"u32"},"attributes":[{"name":"optional"},{"name":"link"}],"identifiers":[]}}],"exports":[{"at":328,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput","getId"]}}],"declarations":[{"at":50,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"PickVertex"},"attributes":[{"name":"link"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":104,"symbol":"getId","flags":6,"func":{"name":"getId","type":{"name":"u32"},"attributes":[{"name":"optional"},{"name":"link"}],"identifiers":[]}},{"at":153,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragId","type":{"name":"u32"},"attributes":[{"name":"location","args":["0"]},{"name":"interpolate","args":["flat"]}]},{"name":"fragIndex","type":{"name":"u32"},"attributes":[{"name":"location","args":["1"]},{"name":"interpolate","args":["flat"]}]}]}},{"at":328,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput","getId"]}}]},
    "shake": [[50,["getVertex","main"]],[104,["getId","main"]],[153,["VertexOutput","main"]],[328,["main"]]],
    "tree": decompressAST([["Skip",0,45],["Skip",50,101],["Opt",104,152,"getId"],["Skip",104,113],["Skip",114,119],["Id",123,128],["Shake",153,323],["Id",164,176],["Attr",182,200],["Id",183,190],["Id",191,199],["Id",201,209],["Attr",225,237],["Id",226,234],["Attr",238,256],["Id",239,250],["Id",251,255],["Id",257,263],["Attr",273,285],["Id",274,282],["Attr",286,304],["Id",287,298],["Id",299,303],["Id",305,314],["Shake",328,588],["Attr",328,335],["Id",329,335],["Id",340,344],["Attr",349,371],["Id",350,357],["Id",358,370],["Id",372,383],["Attr",393,417],["Id",394,401],["Id",402,416],["Id",418,431],["Id",444,456],["Id",466,467],["Id",470,479],["Id",480,491],["Id",493,506],["Id",521,533],["Id",540,541],["Id",542,550],["Id",557,562],["Id",571,572],["Id",573,578]]),
  };
const libs = {"../../../wgsl/use/types": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const main = getSymbol("main");
/* __WGSL_LOADER_GENERATED */