import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/types";
const data = {
    "name": "virtual-pick",
    "code": "use '../../../wgsl/use/types'::{ PickVertex };\r\n\r\n@external fn getVertex(v: u32, i: u32) -> PickVertex {};\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) @interpolate(flat) fragIndex: u32,\r\n};\r\n\r\n@stage(vertex)\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  var v = getVertex(vertexIndex, instanceIndex);\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    v.index,\r\n  );\r\n}\r\n",
    "hash": "bgigxa8kw3",
    "table": {"symbols":["getVertex","VertexOutput","main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["PickVertex"],"imports":[{"name":"PickVertex","imported":"PickVertex"}]}],"declarations":[{"at":50,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"PickVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":106,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragIndex","type":{"name":"u32"},"attributes":[{"name":"location","args":["0"]},{"name":"interpolate","args":["flat"]}]}]}},{"at":233,"symbol":"main","flags":0,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"stage","args":["vertex"]}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput"]}}],"externals":[{"at":50,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"PickVertex"},"attributes":[{"name":"external"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}]},
    "shake": [[50,["getVertex","main"]],[106,["VertexOutput","main"]],[233,["main"]]],
    "tree": decompressAST([["Skip",0,45],["Skip",50,105],["Shake",106,228],["Id",117,129],["Attr",135,153],["Id",136,143],["Id",144,152],["Id",154,162],["Attr",178,190],["Id",179,187],["Attr",191,209],["Id",192,203],["Id",204,208],["Id",210,219],["Shake",233,486],["Attr",233,247],["Id",234,239],["Id",240,246],["Id",252,256],["Attr",261,283],["Id",262,269],["Id",270,282],["Id",284,295],["Attr",305,329],["Id",306,313],["Id",314,328],["Id",330,343],["Id",356,368],["Id",378,379],["Id",382,391],["Id",392,403],["Id",405,418],["Id",433,445],["Id",452,453],["Id",454,462],["Id",469,470],["Id",471,476]]),
  };
const libs = {"../../../wgsl/use/types": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __WGSL_LOADER_GENERATED */