import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/types";
const data = {
    "name": "virtual-solid",
    "code": "use '../../../wgsl/use/types'::{ SolidVertex };\r\n\r\n@link fn getVertex(v: u32, i: u32) -> SolidVertex {};\r\n@optional @link fn toColorSpace(c: vec4<f32>) -> vec4<f32> { return c; }\r\n\r\nstruct VertexOutput {\r\n  @builtin(position) position: vec4<f32>,\r\n  @location(0) fragColor: vec4<f32>,\r\n  @location(1) fragUV: vec4<f32>,\r\n  @location(2) fragST: vec4<f32>,\r\n};\r\n\r\n@vertex\r\nfn main(\r\n  @builtin(vertex_index) vertexIndex: u32,\r\n  @builtin(instance_index) instanceIndex: u32,\r\n) -> VertexOutput {\r\n  let v = getVertex(vertexIndex, instanceIndex);\r\n\r\n  return VertexOutput(\r\n    v.position,\r\n    toColorSpace(v.color),\r\n    v.uv,\r\n    v.st,\r\n  );\r\n}\r\n",
    "hash": 2889880773377643,
    "table": {"symbols":["getVertex","toColorSpace","VertexOutput","main"],"visibles":["main"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]}],"externals":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"link"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":106,"symbol":"toColorSpace","flags":6,"func":{"name":"toColorSpace","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"c","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}}],"exports":[{"at":362,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput","toColorSpace"]}}],"declarations":[{"at":51,"symbol":"getVertex","flags":2,"func":{"name":"getVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"link"}],"parameters":[{"name":"v","type":{"name":"u32"}},{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":106,"symbol":"toColorSpace","flags":6,"func":{"name":"toColorSpace","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"c","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":178,"symbol":"VertexOutput","flags":0,"struct":{"name":"VertexOutput","members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"builtin","args":["position"]}]},{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]},{"name":"fragST","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["2"]}]}]}},{"at":362,"symbol":"main","flags":1,"func":{"name":"main","type":{"name":"VertexOutput"},"attributes":[{"name":"vertex"}],"parameters":[{"name":"vertexIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["vertex_index"]}]},{"name":"instanceIndex","type":{"name":"u32"},"attributes":[{"name":"builtin","args":["instance_index"]}]}],"identifiers":["getVertex","VertexOutput","toColorSpace"]}}]},
    "shake": [[51,["getVertex","main"]],[106,["toColorSpace","main"]],[178,["VertexOutput","main"]],[362,["main"]]],
    "tree": decompressAST([["Skip",0,46],["Skip",51,103],["Opt",106,178,"toColorSpace"],["Skip",106,115],["Skip",116,121],["Id",125,137],["Id",138,139],["Id",174,175],["Shake",178,357],["Id",189,201],["Attr",207,225],["Id",208,215],["Id",216,224],["Id",226,234],["Attr",250,262],["Id",251,259],["Id",263,272],["Attr",288,300],["Id",289,297],["Id",301,307],["Attr",323,335],["Id",324,332],["Id",336,342],["Shake",362,644],["Attr",362,369],["Id",363,369],["Id",374,378],["Attr",383,405],["Id",384,391],["Id",392,404],["Id",406,417],["Attr",427,451],["Id",428,435],["Id",436,450],["Id",452,465],["Id",478,490],["Id",500,501],["Id",504,513],["Id",514,525],["Id",527,540],["Id",555,567],["Id",574,575],["Id",576,584],["Id",591,603],["Id",604,605],["Id",606,611],["Id",619,620],["Id",621,623],["Id",630,631],["Id",632,634]]),
  };
const libs = {"../../../wgsl/use/types": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const main = getSymbol("main");
/* __WGSL_LOADER_GENERATED */