import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
const data = {
    "name": "solid",
    "code": "@external fn getFragment(color: vec4<f32>, uv: vec2<f32>) -> vec4<f32> {};\r\n\r\n@stage(fragment)\r\nfn main(\r\n  @location(0) fragColor: vec4<f32>,\r\n  @location(1) fragUV: vec2<f32>,  \r\n) -> @location(0) vec4<f32> {\r\n  var outColor = fragColor;\r\n\r\n  // TODO: awaiting compound support\r\n  //outColor.xyz *= outColor.a;\r\n  outColor = vec4<f32>(outColor.xyz * outColor.a, outColor.a);\r\n  outColor = getFragment(outColor, fragUV);\r\n\r\n  if (outColor.a <= 0.0) { discard; }\r\n  return outColor;\r\n}\r\n",
    "table": {"hash":"bjqpj34xkx","symbols":["getFragment","main"],"declarations":[{"at":0,"symbol":"getFragment","flags":2,"func":{"name":"getFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":78,"symbol":"main","flags":0,"func":{"name":"main","type":{"name":"vec4","args":[{"name":"f32"}],"attributes":[{"name":"location","args":["0"]}]},"attributes":[{"name":"stage","args":["fragment"]}],"parameters":[{"name":"fragColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["0"]}]},{"name":"fragUV","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"location","args":["1"]}]}],"identifiers":["getFragment"]}}],"externals":[{"at":0,"symbol":"getFragment","flags":2,"func":{"name":"getFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}}]},
    "shake": [[0,["getFragment","main"]],[78,["main"]]],
    "tree": decompressAST([["Skip",0,73],["Shake",78,485],["Attr",78,94],["Id",79,84],["Id",85,93],["Id",99,103],["Attr",108,120],["Id",109,117],["Id",121,130],["Attr",146,158],["Id",147,155],["Id",159,165],["Attr",186,198],["Id",187,195],["Id",218,226],["Id",229,238],["Id",316,324],["Id",337,345],["Id",346,349],["Id",352,360],["Id",361,362],["Id",364,372],["Id",373,374],["Id",380,388],["Id",391,402],["Id",403,411],["Id",413,419],["Id",431,439],["Id",440,441],["Id",473,481]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
/* __WGSL_LOADER_GENERATED */