import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "grid",
    "code": "@link fn getGridValue(i: u32) -> f32;\r\n@link fn getGridDirection(i: u32) -> i32;\r\n@link fn getGridMin(i: u32) -> vec4<f32>;\r\n@link fn getGridMax(i: u32) -> vec4<f32>;\r\n\r\nlet STEP = vec2<f32>(0.0, 1.0);\r\n\r\n@export fn getGridPosition(index: u32) -> vec4<f32> {\r\n  let n = u32(LINE_DETAIL + 1);\r\n\r\n  let i = index / n;\r\n  let v = f32(index % n) / f32(n - 1u);\r\n\r\n  let base = mix(getGridMin(0u), getGridMax(0u), v);\r\n\r\n  let dir = getGridDirection(0u);\r\n  var step: vec4<f32>;\r\n  if      (dir == 0) { step = STEP.yxxx; }\r\n  else if (dir == 1) { step = STEP.xyxx; }\r\n  else if (dir == 2) { step = STEP.xxyx; }\r\n  else               { step = STEP.xxxy; }\r\n\r\n  return base + step * getGridValue(i);\r\n}\r\n",
    "hash": 6740508238345160,
    "table": {"symbols":["getGridValue","getGridDirection","getGridMin","getGridMax","STEP","getGridPosition"],"visibles":["getGridPosition"],"externals":[{"at":0,"symbol":"getGridValue","flags":2,"func":{"name":"getGridValue","type":{"name":"f32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":39,"symbol":"getGridDirection","flags":2,"func":{"name":"getGridDirection","type":{"name":"i32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":82,"symbol":"getGridMin","flags":2,"func":{"name":"getGridMin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":125,"symbol":"getGridMax","flags":2,"func":{"name":"getGridMax","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}],"exports":[{"at":205,"symbol":"getGridPosition","flags":1,"func":{"name":"getGridPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getGridMin","getGridMax","getGridDirection","STEP","getGridValue"]}}],"declarations":[{"at":0,"symbol":"getGridValue","flags":2,"func":{"name":"getGridValue","type":{"name":"f32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":39,"symbol":"getGridDirection","flags":2,"func":{"name":"getGridDirection","type":{"name":"i32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":82,"symbol":"getGridMin","flags":2,"func":{"name":"getGridMin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":125,"symbol":"getGridMax","flags":2,"func":{"name":"getGridMax","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":166,"symbol":"STEP","flags":0,"constant":{"name":"STEP","type":{"name":"auto"},"value":"vec2<f32>(0.0, 1.0)","identifiers":[]}},{"at":205,"symbol":"getGridPosition","flags":1,"func":{"name":"getGridPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getGridMin","getGridMax","getGridDirection","STEP","getGridValue"]}}]},
    "shake": [[0,["getGridValue","getGridPosition"]],[39,["getGridDirection","getGridPosition"]],[82,["getGridMin","getGridPosition"]],[125,["getGridMax","getGridPosition"]],[166,["STEP","getGridPosition"]],[205,["getGridPosition"]]],
    "tree": decompressAST([["Skip",0,36],["Skip",39,79],["Skip",82,122],["Skip",125,165],["Shake",166,201],["Id",174,178],["Shake",205,695],["Skip",205,212],["Id",216,231],["Id",232,237],["Id",266,267],["Id",274,285],["Id",301,302],["Id",305,310],["Id",313,314],["Id",323,324],["Id",331,336],["Id",339,340],["Id",348,349],["Id",366,370],["Id",373,376],["Id",377,387],["Id",393,403],["Id",409,410],["Id",422,425],["Id",428,444],["Id",457,461],["Id",486,489],["Id",498,502],["Id",505,509],["Id",510,514],["Id",530,533],["Id",542,546],["Id",549,553],["Id",554,558],["Id",574,577],["Id",586,590],["Id",593,597],["Id",598,602],["Id",630,634],["Id",637,641],["Id",642,646],["Id",662,666],["Id",669,673],["Id",676,688],["Id",689,690]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getGridPosition = getSymbol("getGridPosition");
/* __WGSL_LOADER_GENERATED */