import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "grid",
    "code": "@external fn getGridValue(i: u32) -> f32;\r\n@external fn getGridDirection(i: u32) -> i32;\r\n@external fn getGridMin(i: u32) -> vec4<f32>;\r\n@external fn getGridMax(i: u32) -> vec4<f32>;\r\n\r\nlet STEP = vec2<f32>(0.0, 1.0);\r\n\r\n@export fn getGridPosition(index: u32) -> vec4<f32> {\r\n  let n = u32(LINE_DETAIL + 1);\r\n\r\n  let i = index / n;\r\n  let v = f32(index % n) / f32(n - 1u);\r\n\r\n  let base = mix(getGridMin(0u), getGridMax(0u), v);\r\n\r\n  let dir = getGridDirection(0u);\r\n  var step: vec4<f32>;\r\n  if      (dir == 0) { step = STEP.yxxx; }\r\n  else if (dir == 1) { step = STEP.xyxx; }\r\n  else if (dir == 2) { step = STEP.xxyx; }\r\n  else               { step = STEP.xxxy; }\r\n\r\n  return base + step * getGridValue(i);\r\n}\r\n",
    "hash": "8h3wxb946w",
    "table": {"symbols":["getGridValue","getGridDirection","getGridMin","getGridMax","STEP","getGridPosition"],"visibles":["getGridPosition"],"declarations":[{"at":0,"symbol":"getGridValue","flags":2,"func":{"name":"getGridValue","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":43,"symbol":"getGridDirection","flags":2,"func":{"name":"getGridDirection","type":{"name":"i32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":90,"symbol":"getGridMin","flags":2,"func":{"name":"getGridMin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":137,"symbol":"getGridMax","flags":2,"func":{"name":"getGridMax","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":182,"symbol":"STEP","flags":0,"constant":{"name":"STEP","type":{"name":"auto"},"value":"vec2<f32>(0.0, 1.0)","identifiers":[]}},{"at":221,"symbol":"getGridPosition","flags":1,"func":{"name":"getGridPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getGridMin","getGridMax","getGridDirection","STEP","getGridValue"]}}],"externals":[{"at":0,"symbol":"getGridValue","flags":2,"func":{"name":"getGridValue","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":43,"symbol":"getGridDirection","flags":2,"func":{"name":"getGridDirection","type":{"name":"i32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":90,"symbol":"getGridMin","flags":2,"func":{"name":"getGridMin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":137,"symbol":"getGridMax","flags":2,"func":{"name":"getGridMax","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}]},
    "shake": [[0,["getGridValue","getGridPosition"]],[43,["getGridDirection","getGridPosition"]],[90,["getGridMin","getGridPosition"]],[137,["getGridMax","getGridPosition"]],[182,["STEP","getGridPosition"]],[221,["getGridPosition"]]],
    "tree": decompressAST([["Skip",0,40],["Skip",43,87],["Skip",90,134],["Skip",137,181],["Shake",182,217],["Id",190,194],["Shake",221,711],["Skip",221,228],["Id",232,247],["Id",248,253],["Id",282,283],["Id",290,301],["Id",317,318],["Id",321,326],["Id",329,330],["Id",339,340],["Id",347,352],["Id",355,356],["Id",364,365],["Id",382,386],["Id",389,392],["Id",393,403],["Id",409,419],["Id",425,426],["Id",438,441],["Id",444,460],["Id",473,477],["Id",502,505],["Id",514,518],["Id",521,525],["Id",526,530],["Id",546,549],["Id",558,562],["Id",565,569],["Id",570,574],["Id",590,593],["Id",602,606],["Id",609,613],["Id",614,618],["Id",646,650],["Id",653,657],["Id",658,662],["Id",678,682],["Id",685,689],["Id",692,704],["Id",705,706]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getGridPosition = getSymbol("getGridPosition");
/* __WGSL_LOADER_GENERATED */