import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "scale",
    "code": "@link fn getScaleValue(i: u32) -> f32;\r\n@link fn getScaleDirection(i: u32) -> i32;\r\n@link fn getScaleOrigin(i: u32) -> vec4<f32>;\r\n\r\nlet STEP = vec2<f32>(0.0, 1.0);\r\n\r\n@export fn getScalePosition(index: u32) -> vec4<f32> {\r\n  \r\n  let dir = getScaleDirection(0u);\r\n\r\n  var step: vec4<f32>;\r\n  if (dir == 0) { step = STEP.yxxx; }\r\n  if (dir == 1) { step = STEP.xyxx; }\r\n  if (dir == 2) { step = STEP.xxyx; }\r\n  if (dir == 3) { step = STEP.xxxy; }\r\n  \r\n  return getScaleOrigin(0u) + step * getScaleValue(index);\r\n}\r\n",
    "hash": 665918758041136,
    "table": {"symbols":["getScaleValue","getScaleDirection","getScaleOrigin","STEP","getScalePosition"],"visibles":["getScalePosition"],"externals":[{"at":0,"symbol":"getScaleValue","flags":2,"func":{"name":"getScaleValue","type":{"name":"f32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":40,"symbol":"getScaleDirection","flags":2,"func":{"name":"getScaleDirection","type":{"name":"i32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":84,"symbol":"getScaleOrigin","flags":2,"func":{"name":"getScaleOrigin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}],"exports":[{"at":168,"symbol":"getScalePosition","flags":1,"func":{"name":"getScalePosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getScaleDirection","STEP","getScaleOrigin","getScaleValue"]}}],"declarations":[{"at":0,"symbol":"getScaleValue","flags":2,"func":{"name":"getScaleValue","type":{"name":"f32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":40,"symbol":"getScaleDirection","flags":2,"func":{"name":"getScaleDirection","type":{"name":"i32"},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":84,"symbol":"getScaleOrigin","flags":2,"func":{"name":"getScaleOrigin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"link"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":129,"symbol":"STEP","flags":0,"constant":{"name":"STEP","type":{"name":"auto"},"value":"vec2<f32>(0.0, 1.0)","identifiers":[]}},{"at":168,"symbol":"getScalePosition","flags":1,"func":{"name":"getScalePosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getScaleDirection","STEP","getScaleOrigin","getScaleValue"]}}]},
    "shake": [[0,["getScaleValue","getScalePosition"]],[40,["getScaleDirection","getScalePosition"]],[84,["getScaleOrigin","getScalePosition"]],[129,["STEP","getScalePosition"]],[168,["getScalePosition"]]],
    "tree": decompressAST([["Skip",0,37],["Skip",40,81],["Skip",84,128],["Shake",129,164],["Id",137,141],["Shake",168,511],["Skip",168,175],["Id",179,195],["Id",196,201],["Id",234,237],["Id",240,257],["Id",272,276],["Id",296,299],["Id",308,312],["Id",315,319],["Id",320,324],["Id",335,338],["Id",347,351],["Id",354,358],["Id",359,363],["Id",374,377],["Id",386,390],["Id",393,397],["Id",398,402],["Id",413,416],["Id",425,429],["Id",432,436],["Id",437,441],["Id",459,473],["Id",480,484],["Id",487,500],["Id",501,506]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getScalePosition = getSymbol("getScalePosition");
/* __WGSL_LOADER_GENERATED */