import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "scale",
    "code": "@external fn getScaleValue(i: u32) -> f32;\r\n@external fn getScaleDirection(i: u32) -> i32;\r\n@external fn getScaleOrigin(i: u32) -> vec4<f32>;\r\n\r\nlet STEP = vec2<f32>(0.0, 1.0);\r\n\r\n@export fn getScalePosition(index: u32) -> vec4<f32> {\r\n  \r\n  let dir = getScaleDirection(0u);\r\n\r\n  var step: vec4<f32>;\r\n  if (dir == 0) { step = STEP.yxxx; }\r\n  if (dir == 1) { step = STEP.xyxx; }\r\n  if (dir == 2) { step = STEP.xxyx; }\r\n  if (dir == 3) { step = STEP.xxxy; }\r\n  \r\n  return getScaleOrigin(0u) + step * getScaleValue(index);\r\n}\r\n",
    "hash": "vqgdqo15te",
    "table": {"symbols":["getScaleValue","getScaleDirection","getScaleOrigin","STEP","getScalePosition"],"visibles":["getScalePosition"],"declarations":[{"at":0,"symbol":"getScaleValue","flags":2,"func":{"name":"getScaleValue","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":44,"symbol":"getScaleDirection","flags":2,"func":{"name":"getScaleDirection","type":{"name":"i32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":92,"symbol":"getScaleOrigin","flags":2,"func":{"name":"getScaleOrigin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":141,"symbol":"STEP","flags":0,"constant":{"name":"STEP","type":{"name":"auto"},"value":"vec2<f32>(0.0, 1.0)","identifiers":[]}},{"at":180,"symbol":"getScalePosition","flags":1,"func":{"name":"getScalePosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getScaleDirection","STEP","getScaleOrigin","getScaleValue"]}}],"externals":[{"at":0,"symbol":"getScaleValue","flags":2,"func":{"name":"getScaleValue","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":44,"symbol":"getScaleDirection","flags":2,"func":{"name":"getScaleDirection","type":{"name":"i32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":92,"symbol":"getScaleOrigin","flags":2,"func":{"name":"getScaleOrigin","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}]},
    "shake": [[0,["getScaleValue","getScalePosition"]],[44,["getScaleDirection","getScalePosition"]],[92,["getScaleOrigin","getScalePosition"]],[141,["STEP","getScalePosition"]],[180,["getScalePosition"]]],
    "tree": decompressAST([["Skip",0,41],["Skip",44,89],["Skip",92,140],["Shake",141,176],["Id",149,153],["Shake",180,523],["Skip",180,187],["Id",191,207],["Id",208,213],["Id",246,249],["Id",252,269],["Id",284,288],["Id",308,311],["Id",320,324],["Id",327,331],["Id",332,336],["Id",347,350],["Id",359,363],["Id",366,370],["Id",371,375],["Id",386,389],["Id",398,402],["Id",405,409],["Id",410,414],["Id",425,428],["Id",437,441],["Id",444,448],["Id",449,453],["Id",471,485],["Id",492,496],["Id",499,512],["Id",513,518]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getScalePosition = getSymbol("getScalePosition");
/* __WGSL_LOADER_GENERATED */