import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "masked",
    "code": "@optional @link fn getMask(uv: vec2<f32>) -> f32 { return 1.0; };\r\n@optional @link fn getTexture(uv: vec2<f32>) -> vec4<f32> { return vec4<f32>(1.0, 1.0, 1.0, 1.0); };\r\n\r\n@export fn getMaskedFragment(color: vec4<f32>, uv: vec4<f32>, st: vec4<f32>) -> vec4<f32> {\r\n  let t = getTexture(uv.xy);\r\n  let m = getMask(uv.xy);\r\n\r\n  var c = color;\r\n  \r\n  if (HAS_ALPHA_TO_COVERAGE) {\r\n    c = vec4<f32>(c.xyz * t.xyz, c.a * m * t.a);\r\n  }\r\n  else {\r\n    c = c * t * clamp(m, 0.0, 1.0);\r\n  }\r\n\r\n  return c;\r\n}\r\n",
    "hash": 3103615161566156,
    "table": {"symbols":["getMask","getTexture","getMaskedFragment"],"visibles":["getMaskedFragment"],"externals":[{"at":0,"symbol":"getMask","flags":6,"func":{"name":"getMask","type":{"name":"f32"},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":67,"symbol":"getTexture","flags":6,"func":{"name":"getTexture","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}}],"exports":[{"at":171,"symbol":"getMaskedFragment","flags":1,"func":{"name":"getMaskedFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"st","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":["getTexture","getMask"]}}],"declarations":[{"at":0,"symbol":"getMask","flags":6,"func":{"name":"getMask","type":{"name":"f32"},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":67,"symbol":"getTexture","flags":6,"func":{"name":"getTexture","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"link"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":171,"symbol":"getMaskedFragment","flags":1,"func":{"name":"getMaskedFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"st","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":["getTexture","getMask"]}}]},
    "shake": [[0,["getMask","getMaskedFragment"]],[67,["getTexture","getMaskedFragment"]],[171,["getMaskedFragment"]]],
    "tree": decompressAST([["Opt",0,64,"getMask"],["Skip",0,9],["Skip",10,15],["Id",19,26],["Id",27,29],["Opt",67,166,"getTexture"],["Skip",67,76],["Skip",77,82],["Id",86,96],["Id",97,99],["Shake",171,500],["Skip",171,178],["Id",182,199],["Id",200,205],["Id",218,220],["Id",233,235],["Id",270,271],["Id",274,284],["Id",285,287],["Id",288,290],["Id",300,301],["Id",304,311],["Id",312,314],["Id",315,317],["Id",329,330],["Id",333,338],["Id",351,372],["Id",381,382],["Id",395,396],["Id",397,400],["Id",403,404],["Id",405,408],["Id",410,411],["Id",412,413],["Id",416,417],["Id",420,421],["Id",422,423],["Id",446,447],["Id",450,451],["Id",454,455],["Id",458,463],["Id",464,465],["Id",495,496]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getMaskedFragment = getSymbol("getMaskedFragment");
/* __WGSL_LOADER_GENERATED */