import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "masked",
    "code": "@optional @external fn getMask(uv: vec2<f32>) -> f32 { return 1.0; };\r\n@optional @external fn getTexture(uv: vec2<f32>) -> vec4<f32> { return vec4<f32>(1.0, 1.0, 1.0, 1.0); };\r\n\r\n@export fn getMaskedFragment(color: vec4<f32>, uv: vec2<f32>) -> vec4<f32> {\r\n  let t = getTexture(uv);\r\n  let m = getMask(uv);\r\n\r\n  if (HAS_ALPHA_TO_COVERAGE) {\r\n    return vec4<f32>(color.xyz * t.xyz, color.a * m * t.a);\r\n  }\r\n  else {\r\n    return color * t * m;\r\n  }\r\n}\r\n",
    "hash": "vq55wgshbf",
    "table": {"symbols":["getMask","getTexture","getMaskedFragment"],"visibles":["getMaskedFragment"],"declarations":[{"at":0,"symbol":"getMask","flags":6,"func":{"name":"getMask","type":{"name":"f32"},"attributes":[{"name":"optional"},{"name":"external"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":71,"symbol":"getTexture","flags":6,"func":{"name":"getTexture","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"external"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":179,"symbol":"getMaskedFragment","flags":1,"func":{"name":"getMaskedFragment","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":["getTexture","getMask"]}}],"externals":[{"at":0,"symbol":"getMask","flags":6,"func":{"name":"getMask","type":{"name":"f32"},"attributes":[{"name":"optional"},{"name":"external"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":71,"symbol":"getTexture","flags":6,"func":{"name":"getTexture","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"optional"},{"name":"external"}],"parameters":[{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}],"identifiers":[]}}]},
    "shake": [[0,["getMask","getMaskedFragment"]],[71,["getTexture","getMaskedFragment"]],[179,["getMaskedFragment"]]],
    "tree": decompressAST([["Opt",0,68,"getMask"],["Skip",0,9],["Skip",10,19],["Id",23,30],["Id",31,33],["Opt",71,174,"getTexture"],["Skip",71,80],["Skip",81,90],["Id",94,104],["Id",105,107],["Shake",179,451],["Skip",179,186],["Id",190,207],["Id",208,213],["Id",226,228],["Id",263,264],["Id",267,277],["Id",278,280],["Id",290,291],["Id",294,301],["Id",302,304],["Id",316,337],["Id",363,368],["Id",369,372],["Id",375,376],["Id",377,380],["Id",382,387],["Id",388,389],["Id",392,393],["Id",396,397],["Id",398,399],["Id",429,434],["Id",437,438],["Id",441,442]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getMaskedFragment = getSymbol("getMaskedFragment");
/* __WGSL_LOADER_GENERATED */