import {decompressAST, bindEntryPoint} from "../../../shader/wgsl";
import m0 from "../../use/viewwgsl";
import m1 from "../../use/typeswgsl";
import m2 from "../../codec/octahedralwgsl";
const t = {"symbols":["getAlbedo","getNormal","getMaterial","getEmissive","getDepth","getEmissiveFragment"],"visibles":["getEmissiveFragment"],"modules":[{"at":0,"name":"../../../wgsl/use/view","symbols":["getViewPosition","clipToWorld","to3D"],"imports":[{"name":"getViewPosition","imported":"getViewPosition"},{"name":"clipToWorld","imported":"clipToWorld"},{"name":"to3D","imported":"to3D"}]},{"at":0,"name":"../../../wgsl/use/types","symbols":["Light","SurfaceFragment"],"imports":[{"name":"Light","imported":"Light"},{"name":"SurfaceFragment","imported":"SurfaceFragment"}]},{"at":0,"name":"../../../wgsl/codec/octahedral","symbols":["decodeOctahedral"],"imports":[{"name":"decodeOctahedral","imported":"decodeOctahedral"}]}],"externals":[{"at":194,"symbol":"getAlbedo","flags":2,"func":{"name":"getAlbedo","type":"vec4<f32>","attr":["link"],"parameters":[{"name":"uv","type":"vec2<f32>"}]}},{"at":243,"symbol":"getNormal","flags":2,"func":{"name":"getNormal","type":"vec4<f32>","attr":["link"],"parameters":[{"name":"uv","type":"vec2<f32>"}]}},{"at":292,"symbol":"getMaterial","flags":2,"func":{"name":"getMaterial","type":"vec4<f32>","attr":["link"],"parameters":[{"name":"uv","type":"vec2<f32>"}]}},{"at":343,"symbol":"getEmissive","flags":2,"func":{"name":"getEmissive","type":"vec4<f32>","attr":["link"],"parameters":[{"name":"uv","type":"vec2<f32>"}]}},{"at":394,"symbol":"getDepth","flags":2,"func":{"name":"getDepth","type":"f32","attr":["link"],"parameters":[{"name":"uv","type":"vec2<f32>"}]}}],"exports":[{"at":438,"symbol":"getEmissiveFragment","flags":1,"func":{"name":"getEmissiveFragment","type":"vec4<f32>","attr":["export"],"parameters":[{"name":"uv","type":"vec2<f32>"},{"name":"index","type":"u32"}],"identifiers":["getEmissive"]}}],"linkable":{"getAlbedo":true,"getNormal":true,"getMaterial":true,"getEmissive":true,"getDepth":true}}; const data = {
  "name": "emissive",
  "code": "use '../../../wgsl/use/view'::{ getViewPosition, clipToWorld, to3D };\r\nuse '../../../wgsl/use/types'::{ Light, SurfaceFragment };\r\nuse '../../../wgsl/codec/octahedral'::{ decodeOctahedral };\r\n\r\n@link fn getAlbedo(uv: vec2<f32>) -> vec4<f32>;\r\n@link fn getNormal(uv: vec2<f32>) -> vec4<f32>;\r\n@link fn getMaterial(uv: vec2<f32>) -> vec4<f32>;\r\n@link fn getEmissive(uv: vec2<f32>) -> vec4<f32>;\r\n@link fn getDepth(uv: vec2<f32>) -> f32;\r\n\r\n@export fn getEmissiveFragment(\r\n  uv: vec2<f32>,\r\n  index: u32,\r\n) -> vec4<f32> {\r\n  return getEmissive(uv);\r\n}\r\n",
  "hash": 6135766577211068,
  "table": t,
  "shake": [[194,[0]],[243,[1]],[292,[2]],[343,[3,5]],[394,[4]],[438,[5]]],
  "tree": decompressAST([[1,0,68],[1,71,128],[1,60,118],[1,63,109],[1,49,95],[1,49,97],[1,51,99],[1,51,90],[0,44,156],[1,0,7],[2,11,30],[2,24,26],[2,18,23],[2,40,51],[2,12,14]], t.symbols),
};
const libs = {"../../../wgsl/use/view": m0, "../../../wgsl/use/types": m1, "../../../wgsl/codec/octahedral": m2};
const getSymbol = (entry) => ({ module: bindEntryPoint(data, entry), libs });
export default getSymbol();
export const getEmissiveFragment = getSymbol("getEmissiveFragment");
/* __WGSL_LOADER_GENERATED */