import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
import m0 from "../../gen-wgsl/use/types";
import m1 from "../../gen-wgsl/fragment/pbr";
const data = {
    "name": "lights-default",
    "code": "use '../../wgsl/use/types'::{ Light, Radiance };\r\nuse '../../wgsl/fragment/pbr'::{ PBR };\r\n\r\n@infer type T;\r\n@link fn applyLight(\r\n  N: vec3<f32>,\r\n  V: vec3<f32>,\r\n  light: Light,\r\n  position: vec3<f32>,\r\n  ao: f32,\r\n  @infer(T) params: T,\r\n) -> Radiance {}\r\n\r\n@export fn applyLights(\r\n  N: vec3<f32>,\r\n  V: vec3<f32>,\r\n  position: vec3<f32>,\r\n  ao: f32,\r\n  params: T,\r\n) -> vec3<f32> {\r\n\r\n  var radiance: vec3<f32> = vec3<f32>(0.0);\r\n\r\n  var light = Light(\r\n    vec4<f32>(0.0, 0.0, 0.0, 1.0),\r\n    vec4<f32>(-0.267, -3*0.267, -2*0.267, 0.0),\r\n    vec4<f32>(0.0),\r\n    vec4<f32>(-1.0, 0.0, 0.0, 0.0),\r\n    vec4<f32>(1.0),\r\n    1.0,\r\n    1,\r\n  );\r\n\r\n  return applyLight(N, V, light, position, ao, params).light;\r\n}\r\n",
    "hash": 5670039191677399,
    "table": {"symbols":["T","applyLight","applyLights"],"visibles":["applyLights"],"modules":[{"at":0,"name":"../../wgsl/use/types","symbols":["Light","Radiance"],"imports":[{"name":"Light","imported":"Light"},{"name":"Radiance","imported":"Radiance"}]},{"at":0,"name":"../../wgsl/fragment/pbr","symbols":["PBR"],"imports":[{"name":"PBR","imported":"PBR"}]}],"externals":[{"at":109,"symbol":"applyLight","flags":2,"func":{"name":"applyLight","type":{"name":"Radiance"},"attributes":[{"name":"link"}],"parameters":[{"name":"N","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"V","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"light","type":{"name":"Light"}},{"name":"position","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"ao","type":{"name":"f32"}},{"name":"params","type":{"name":"T"},"attributes":[{"name":"infer","args":["T"]}]}],"identifiers":[],"inferred":[{"name":"T","at":5}]}}],"exports":[{"at":262,"symbol":"applyLights","flags":1,"func":{"name":"applyLights","type":{"name":"vec3","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"N","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"V","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"position","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"ao","type":{"name":"f32"}},{"name":"params","type":{"name":"T"}}],"identifiers":["applyLight"]}}],"declarations":[{"at":93,"symbol":"T","flags":16,"alias":{"name":"T","type":{"name":"T"},"attributes":[{"name":"infer"}]}},{"at":109,"symbol":"applyLight","flags":2,"func":{"name":"applyLight","type":{"name":"Radiance"},"attributes":[{"name":"link"}],"parameters":[{"name":"N","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"V","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"light","type":{"name":"Light"}},{"name":"position","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"ao","type":{"name":"f32"}},{"name":"params","type":{"name":"T"},"attributes":[{"name":"infer","args":["T"]}]}],"identifiers":[],"inferred":[{"name":"T","at":5}]}},{"at":262,"symbol":"applyLights","flags":1,"func":{"name":"applyLights","type":{"name":"vec3","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"N","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"V","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"position","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"ao","type":{"name":"f32"}},{"name":"params","type":{"name":"T"}}],"identifiers":["applyLight"]}}]},
    "shake": [[93,["T"]],[109,["applyLight","applyLights"]],[262,["applyLights"]]],
    "tree": decompressAST([["Skip",0,47],["Skip",50,88],["Skip",93,107],["Skip",109,258],["Shake",262,714],["Skip",262,269],["Id",273,284],["Id",289,290],["Id",306,307],["Id",323,331],["Id",347,349],["Id",359,365],["Id",367,368],["Id",397,405],["Id",444,449],["Id",452,457],["Id",659,669],["Id",670,671],["Id",673,674],["Id",676,681],["Id",683,691],["Id",693,695],["Id",697,703],["Id",705,710]]),
  };
const libs = {"../../wgsl/use/types": m0, "../../wgsl/fragment/pbr": m1};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const applyLights = getSymbol("applyLights");
/* __WGSL_LOADER_GENERATED */