import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wlsl";
import m0 from "../../../gen-wgsl/use/types";
import m1 from "../../../gen-wgsl/use/view";
import m2 from "../../../gen-wgsl/geometry/quad";
const data = {
    "name": "quad",
    "code": "use '../../../wgsl/use/types'::{ SolidVertex };\r\nuse '../../../wgsl/use/view'::{ viewUniforms, worldToClip, getPerspectiveScale }; \r\nuse '../../../wgsl/geometry/quad'::{ getQuadUV };\r\n\r\n@external fn getPosition(i: i32) -> vec4<f32> {};\r\n@external fn getColor(i: i32) -> vec4<f32> {};\r\n@external fn getSize(i: i32) -> vec2<f32> {};\r\n@external fn getDepth(i: i32) -> f32 {};\r\n\r\n@export fn getQuadVertex(vertexIndex: i32, instanceIndex: i32) -> SolidVertex {\r\n  var position = getPosition(instanceIndex);\r\n  var color = getColor(instanceIndex);\r\n  var size = getSize(instanceIndex);\r\n  var depth = getDepth(instanceIndex);\r\n\r\n  var center = worldToClip(position);\r\n\r\n  var uv = getQuadUV(vertexIndex);\r\n  var xy = uv * 2.0 - 1.0;\r\n  \r\n  // Lerp between fixed size and full perspective.\r\n  var pixelScale = getPerspectiveScale(center.w, depth);\r\n  // TODO: awaiting compound support\r\n  //size *= pixelScale;\r\n  size = size * pixelScale;\r\n\r\n  if (HAS_EDGE_BLEED) {\r\n    xy = xy * (size + 0.5) / size;\r\n    uv = xy * .5 + .5;\r\n  }\r\n\r\n  // TODO: awaiting compound support\r\n  //center.xy += xy * size * viewUniforms.viewResolution * center.w;\r\n  center = vec4<f32>(center.xy + xy * size * viewUniforms.viewResolution * center.w, center.zw);\r\n\r\n  return SolidVertex(\r\n    center,\r\n    color,\r\n    uv\r\n  );\r\n}",
    "table": {"hash":"knoyywh5cm","symbols":["getPosition","getColor","getSize","getDepth","getQuadVertex"],"visibles":["getQuadVertex"],"modules":[{"at":0,"name":"../../../wgsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]},{"at":0,"name":"../../../wgsl/use/view","symbols":["viewUniforms","worldToClip","getPerspectiveScale"],"imports":[{"name":"viewUniforms","imported":"viewUniforms"},{"name":"worldToClip","imported":"worldToClip"},{"name":"getPerspectiveScale","imported":"getPerspectiveScale"}]},{"at":0,"name":"../../../wgsl/geometry/quad","symbols":["getQuadUV"],"imports":[{"name":"getQuadUV","imported":"getQuadUV"}]}],"declarations":[{"at":186,"symbol":"getPosition","flags":2,"func":{"name":"getPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":237,"symbol":"getColor","flags":2,"func":{"name":"getColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":285,"symbol":"getSize","flags":2,"func":{"name":"getSize","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":332,"symbol":"getDepth","flags":2,"func":{"name":"getDepth","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":376,"symbol":"getQuadVertex","flags":1,"func":{"name":"getQuadVertex","type":{"name":"SolidVertex"},"attributes":[{"name":"export"}],"parameters":[{"name":"vertexIndex","type":{"name":"i32"}},{"name":"instanceIndex","type":{"name":"i32"}}],"identifiers":["getPosition","getColor","getSize","getDepth"]}}],"externals":[{"at":186,"symbol":"getPosition","flags":2,"func":{"name":"getPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":237,"symbol":"getColor","flags":2,"func":{"name":"getColor","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":285,"symbol":"getSize","flags":2,"func":{"name":"getSize","type":{"name":"vec2","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}},{"at":332,"symbol":"getDepth","flags":2,"func":{"name":"getDepth","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"i32"}}],"identifiers":[]}}]},
    "shake": [[186,["getPosition","getQuadVertex"]],[237,["getColor","getQuadVertex"]],[285,["getSize","getQuadVertex"]],[332,["getDepth","getQuadVertex"]],[376,["getQuadVertex"]]],
    "tree": decompressAST([["Skip",0,46],["Skip",49,129],["Skip",133,181],["Skip",186,234],["Skip",237,282],["Skip",285,329],["Skip",332,371],["Shake",376,1299],["Skip",376,383],["Id",387,400],["Id",401,412],["Id",419,432],["Id",442,453],["Id",463,471],["Id",474,485],["Id",486,499],["Id",509,514],["Id",517,525],["Id",526,539],["Id",549,553],["Id",556,563],["Id",564,577],["Id",587,592],["Id",595,603],["Id",604,617],["Id",629,635],["Id",638,649],["Id",650,658],["Id",670,672],["Id",675,684],["Id",685,696],["Id",706,708],["Id",711,713],["Id",790,800],["Id",803,822],["Id",823,829],["Id",830,831],["Id",833,838],["Id",907,911],["Id",914,918],["Id",921,931],["Id",942,956],["Id",965,967],["Id",970,972],["Id",976,980],["Id",990,994],["Id",1001,1003],["Id",1006,1008],["Id",1138,1144],["Id",1157,1163],["Id",1164,1166],["Id",1169,1171],["Id",1174,1178],["Id",1181,1193],["Id",1194,1208],["Id",1211,1217],["Id",1218,1219],["Id",1221,1227],["Id",1228,1230],["Id",1245,1256],["Id",1263,1269],["Id",1276,1281],["Id",1288,1290]]),
  };
const libs = {"../../../wgsl/use/types": m0, "../../../wgsl/use/view": m1, "../../../wgsl/geometry/quad": m2};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getQuadVertex = getSymbol("getQuadVertex");
/* __WGSL_LOADER_GENERATED */