import {parseBundle} from "../../../shader";
import {decompressAST} from "../../../shader/wgsl";
import m0 from "../../../gen-wgsl/use/view";
const data = {
    "name": "tick",
    "code": "use '../../../wgsl/use/view'::{ worldToClip, getWorldScale };\r\n\r\n@external fn transformPosition(p: vec4<f32>) -> vec4<f32>;\r\n\r\n@external fn getPosition(i: u32) -> vec4<f32>;\r\n@external fn getOffset(i: u32) -> vec4<f32>;\r\n@external fn getDepth(i: u32) -> f32;\r\n@external fn getSize(i: u32) -> f32;\r\n\r\nlet EPSILON: f32 = 0.001;\r\n\r\n@export fn getTickPosition(index: u32) -> vec4<f32> {\r\n  let offset = getOffset(index);\r\n  let depth = getDepth(index);\r\n  let size = getSize(index);\r\n\r\n  let n = u32(LINE_DETAIL + 1);\r\n  let v = f32(index % n) / f32(LINE_DETAIL) - 0.5;\r\n\r\n  let anchor = getPosition(index / n);\r\n  \r\n  let center = transformPosition(anchor);\r\n  let adj = transformPosition(anchor + offset * EPSILON);\r\n\r\n  let tangent = normalize(adj.xyz - center.xyz);\r\n  \r\n  let c = worldToClip(center);\r\n  let s = getWorldScale(c.w, depth);\r\n\r\n  return center + vec4<f32>(tangent * size * v * s, 0.0);\r\n}\r\n",
    "hash": "q33uq26c6o",
    "table": {"symbols":["transformPosition","getPosition","getOffset","getDepth","getSize","EPSILON","getTickPosition"],"visibles":["getTickPosition"],"modules":[{"at":0,"name":"../../../wgsl/use/view","symbols":["worldToClip","getWorldScale"],"imports":[{"name":"worldToClip","imported":"worldToClip"},{"name":"getWorldScale","imported":"getWorldScale"}]}],"declarations":[{"at":65,"symbol":"transformPosition","flags":2,"func":{"name":"transformPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"p","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":127,"symbol":"getPosition","flags":2,"func":{"name":"getPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":175,"symbol":"getOffset","flags":2,"func":{"name":"getOffset","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":221,"symbol":"getDepth","flags":2,"func":{"name":"getDepth","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":260,"symbol":"getSize","flags":2,"func":{"name":"getSize","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":296,"symbol":"EPSILON","flags":0,"constant":{"name":"EPSILON","type":{"name":"f32"},"value":"0.001","identifiers":[]}},{"at":329,"symbol":"getTickPosition","flags":1,"func":{"name":"getTickPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"export"}],"parameters":[{"name":"index","type":{"name":"u32"}}],"identifiers":["getOffset","getDepth","getSize","getPosition","transformPosition","EPSILON"]}}],"externals":[{"at":65,"symbol":"transformPosition","flags":2,"func":{"name":"transformPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"p","type":{"name":"vec4","args":[{"name":"f32"}]}}],"identifiers":[]}},{"at":127,"symbol":"getPosition","flags":2,"func":{"name":"getPosition","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":175,"symbol":"getOffset","flags":2,"func":{"name":"getOffset","type":{"name":"vec4","args":[{"name":"f32"}]},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":221,"symbol":"getDepth","flags":2,"func":{"name":"getDepth","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}},{"at":260,"symbol":"getSize","flags":2,"func":{"name":"getSize","type":{"name":"f32"},"attributes":[{"name":"external"}],"parameters":[{"name":"i","type":{"name":"u32"}}],"identifiers":[]}}]},
    "shake": [[65,["transformPosition","getTickPosition"]],[127,["getPosition","getTickPosition"]],[175,["getOffset","getTickPosition"]],[221,["getDepth","getTickPosition"]],[260,["getSize","getTickPosition"]],[296,["EPSILON","getTickPosition"]],[329,["getTickPosition"]]],
    "tree": decompressAST([["Skip",0,60],["Skip",65,122],["Skip",127,172],["Skip",175,218],["Skip",221,257],["Skip",260,295],["Shake",296,325],["Id",304,311],["Shake",329,903],["Skip",329,336],["Id",340,355],["Id",356,361],["Id",390,396],["Id",399,408],["Id",409,414],["Id",424,429],["Id",432,440],["Id",441,446],["Id",456,460],["Id",463,470],["Id",471,476],["Id",488,489],["Id",496,507],["Id",521,522],["Id",529,534],["Id",537,538],["Id",546,557],["Id",575,581],["Id",584,595],["Id",596,601],["Id",604,605],["Id",619,625],["Id",628,645],["Id",646,652],["Id",662,665],["Id",668,685],["Id",686,692],["Id",695,701],["Id",704,711],["Id",723,730],["Id",733,742],["Id",743,746],["Id",747,750],["Id",753,759],["Id",760,763],["Id",777,778],["Id",781,792],["Id",793,799],["Id",809,810],["Id",813,826],["Id",827,828],["Id",829,830],["Id",832,837],["Id",852,858],["Id",871,878],["Id",881,885],["Id",888,889],["Id",892,893]]),
  };
const libs = {"../../../wgsl/use/view": m0};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getTickPosition = getSymbol("getTickPosition");
/* __WGSL_LOADER_GENERATED */