import { decompressAST } from "../../../shader/transform/ast";
import * as m0 from "../../use/view";
import * as m1 from "../../use/picking";
import * as m2 from "../../use/light";
const data = {
  "name": "mesh",
  "code": "#pragma import {worldToClip} from '../../../glsl/use/view'\r\n#pragma import {pickingUniforms} from '../../../glsl/use/picking';\r\n#pragma import {lightUniforms} from '../../../glsl/use/light';\r\n\r\nlayout(location = 0) in vec4 position;\r\nlayout(location = 1) in vec4 normal;\r\nlayout(location = 2) in vec4 color;\r\nlayout(location = 3) in vec2 uv;\r\n\r\n#ifdef IS_PICKING\r\nlayout(location = 0) out flat uint fragIndex;\r\n#else\r\nlayout(location = 0) out vec4 fragColor;\r\nlayout(location = 1) out vec2 fragUV;\r\n\r\nlayout(location = 2) out vec3 fragNormal;\r\nlayout(location = 3) out vec3 fragPosition;\r\n#endif\r\n\r\nvoid main() {\r\n  int instanceIndex = gl_InstanceIndex;\r\n  gl_Position = worldToClip(position);\r\n#ifdef IS_PICKING\r\n  fragIndex = uint(instanceIndex);\r\n#else\r\n  fragColor = color;\r\n  fragUV = uv;\r\n\r\n  fragNormal = normal.xyz;\r\n  fragPosition = position.xyz;\r\n#endif\r\n}\r\n",
  "table": {"hash":"3jcb4u3iok","symbols":["main","position","normal","color","uv","fragIndex","fragColor","fragUV","fragNormal","fragPosition"],"visibles":[],"globals":[],"externals":[],"modules":[{"at":0,"name":"@use-gpu/glsl/use/view","symbols":["worldToClip"],"imports":[{"name":"worldToClip","imported":"worldToClip"}]},{"at":0,"name":"@use-gpu/glsl/use/picking","symbols":["pickingUniforms"],"imports":[{"name":"pickingUniforms","imported":"pickingUniforms"}]},{"at":0,"name":"@use-gpu/glsl/use/light","symbols":["lightUniforms"],"imports":[{"name":"lightUniforms","imported":"lightUniforms"}]}],"functions":[{"at":599,"symbols":["main"],"identifiers":["position","fragIndex","fragColor","color","fragUV","uv","fragNormal","normal","fragPosition"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}}],"declarations":[{"at":194,"symbols":["position"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","in"]},"locals":[{"name":"position","expr":null}]}},{"at":234,"symbols":["normal"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 1)","in"]},"locals":[{"name":"normal","expr":null}]}},{"at":272,"symbols":["color"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 2)","in"]},"locals":[{"name":"color","expr":null}]}},{"at":309,"symbols":["uv"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 3)","in"]},"locals":[{"name":"uv","expr":null}]}},{"at":364,"symbols":["fragIndex"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uint","qualifiers":["layout(location = 0)","out","flat"]},"locals":[{"name":"fragIndex","expr":null}]}},{"at":418,"symbols":["fragColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"fragColor","expr":null}]}},{"at":460,"symbols":["fragUV"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 1)","out"]},"locals":[{"name":"fragUV","expr":null}]}},{"at":501,"symbols":["fragNormal"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec3","qualifiers":["layout(location = 2)","out"]},"locals":[{"name":"fragNormal","expr":null}]}},{"at":544,"symbols":["fragPosition"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec3","qualifiers":["layout(location = 3)","out"]},"locals":[{"name":"fragPosition","expr":null}]}}]},
  "shake": [[194,["position","main"]],[234,["normal","main"]],[272,["color","main"]],[309,["uv","main"]],[364,["fragIndex","main"]],[418,["fragColor","main"]],[460,["fragUV","main"]],[501,["fragNormal","main"]],[544,["fragPosition","main"]],[599,["main"]]],
  "tree": decompressAST([["Skip",0,59],["Skip",60,127],["Skip",128,191],["Shake",194,232],["Id",201,209],["Id",223,231],["Shake",234,270],["Id",241,249],["Id",263,269],["Shake",272,307],["Id",279,287],["Id",301,306],["Shake",309,341],["Id",316,324],["Id",338,340],["Shake",364,409],["Id",371,379],["Id",399,408],["Shake",418,458],["Id",425,433],["Id",448,457],["Shake",460,497],["Id",467,475],["Id",490,496],["Shake",501,542],["Id",508,516],["Id",531,541],["Shake",544,587],["Id",551,559],["Id",574,586],["Shake",599,866],["Id",604,608],["Id",620,633],["Id",636,652],["Id",657,668],["Id",671,682],["Id",683,691],["Id",716,725],["Id",733,746],["Id",759,768],["Id",771,776],["Id",781,787],["Id",790,792],["Id",799,809],["Id",812,818],["Id",827,839],["Id",842,850]])
};
const libs = { "@use-gpu/glsl/use/view": m0, "@use-gpu/glsl/use/picking": m1, "@use-gpu/glsl/use/light": m2 };
const getSymbol = (entry?: string) => ({ module: data, libs, entry });
export default getSymbol();
