import { decompressAST } from "../../../shader/transform/ast";
import * as m0 from "../../../../../glsl/use/types";
const data = {
  "name": "virtual",
  "code": "#pragma import {SolidVertex} from '../../../glsl/use/types'\r\n\r\nSolidVertex getVertex(int, int);\r\n\r\n#ifdef IS_PICKING\r\nlayout(location = 0) out flat uint fragIndex;\r\n#else\r\nlayout(location = 0) out vec4 fragColor;\r\nlayout(location = 1) out vec2 fragUV;\r\n#endif\r\n\r\nvoid main() {\r\n  int vertexIndex = gl_VertexIndex;\r\n  int instanceIndex = gl_InstanceIndex;\r\n\r\n  SolidVertex v = getVertex(vertexIndex, instanceIndex);\r\n\r\n  gl_Position = v.position;\r\n#ifdef IS_PICKING\r\n  fragIndex = uint(instanceIndex);\r\n#else\r\n  fragColor = v.color;\r\n  fragUV = v.uv;\r\n#endif\r\n}",
  "table": {"hash":"lqls389fdi","symbols":["main","getVertex","fragIndex","fragColor","fragUV"],"visibles":[],"globals":[],"externals":[{"at":63,"symbols":["getVertex"],"identifiers":[],"flags":0,"prototype":{"name":"getVertex","type":{"name":"SolidVertex","qualifiers":[]},"parameters":["int"]}}],"modules":[{"at":0,"name":"../../../glsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]}],"functions":[{"at":263,"symbols":["main"],"identifiers":["getVertex","fragIndex","fragColor","fragUV"],"flags":0,"prototype":{"name":"main","type":{"name":"void","qualifiers":[]},"parameters":[]}}],"declarations":[{"at":63,"symbols":["getVertex"],"identifiers":[],"flags":0,"prototype":{"name":"getVertex","type":{"name":"SolidVertex","qualifiers":[]},"parameters":["int"]}},{"at":118,"symbols":["fragIndex"],"identifiers":[],"flags":0,"variable":{"type":{"name":"uint","qualifiers":["layout(location = 0)","out","flat"]},"locals":[{"name":"fragIndex","expr":null}]}},{"at":172,"symbols":["fragColor"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec4","qualifiers":["layout(location = 0)","out"]},"locals":[{"name":"fragColor","expr":null}]}},{"at":214,"symbols":["fragUV"],"identifiers":[],"flags":0,"variable":{"type":{"name":"vec2","qualifiers":["layout(location = 1)","out"]},"locals":[{"name":"fragUV","expr":null}]}}]},
  "shake": [[63,["getVertex","main"]],[118,["fragIndex","main"]],[172,["fragColor","main"]],[214,["fragUV","main"]],[263,["main"]]],
  "tree": decompressAST([["Skip",0,60],["Shake",63,95],["Id",63,74],["Id",75,84],["Shake",118,163],["Id",125,133],["Id",153,162],["Shake",172,212],["Id",179,187],["Id",202,211],["Shake",214,251],["Id",221,229],["Id",244,250],["Shake",263,560],["Id",268,272],["Id",284,295],["Id",298,312],["Id",321,334],["Id",337,353],["Id",360,371],["Id",372,373],["Id",376,385],["Id",386,397],["Id",399,412],["Id",420,431],["Id",434,435],["Id",468,477],["Id",485,498],["Id",511,520],["Id",523,524],["Id",535,541],["Id",544,545]])
};
const libs = { "../../../glsl/use/types": m0 };
const getSymbol = (entry?: string) => ({ module: data, libs, entry });
export default getSymbol();
