import {parseBundle} from "../../shader";
import {decompressAST} from "../../shader/wgsl";
const data = {
    "name": "types",
    "code": "@export struct PickVertex {\r\n  position: vec4<f32>,\r\n  index: u32,\r\n};\r\n\r\n@export struct SolidVertex {\r\n  position: vec4<f32>,\r\n  color: vec4<f32>,\r\n  uv: vec2<f32>,\r\n  index: u32,\r\n};\r\n\r\n@export struct UIVertex {\r\n  position: vec4<f32>,\r\n\r\n  uv: vec2<f32>,\r\n  sdfConfig: vec4<f32>,\r\n  sdfUV: vec2<f32>,\r\n  textureUV: vec2<f32>,\r\n  repeat: i32,\r\n\r\n  mode: i32,\r\n  layout: vec4<f32>,\r\n  radius: vec4<f32>,\r\n  border: vec4<f32>,\r\n  stroke: vec4<f32>,\r\n  fill: vec4<f32>,\r\n\r\n  index: u32,\r\n};\r\n\r\n@export struct MeshVertex {\r\n  position: vec4<f32>,\r\n  normal: vec3<f32>,\r\n  color: vec4<f32>,\r\n  uv: vec2<f32>,\r\n};\r\n",
    "hash": "jx0r0itczz",
    "table": {"symbols":["PickVertex","SolidVertex","UIVertex","MeshVertex"],"visibles":["PickVertex","SolidVertex","UIVertex","MeshVertex"],"declarations":[{"at":0,"symbol":"PickVertex","flags":1,"struct":{"name":"PickVertex","attributes":[{"name":"export"}],"members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"index","type":{"name":"u32"}}]}},{"at":74,"symbol":"SolidVertex","flags":1,"struct":{"name":"SolidVertex","attributes":[{"name":"export"}],"members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}},{"name":"index","type":{"name":"u32"}}]}},{"at":188,"symbol":"UIVertex","flags":1,"struct":{"name":"UIVertex","attributes":[{"name":"export"}],"members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}},{"name":"sdfConfig","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"sdfUV","type":{"name":"vec2","args":[{"name":"f32"}]}},{"name":"textureUV","type":{"name":"vec2","args":[{"name":"f32"}]}},{"name":"repeat","type":{"name":"i32"}},{"name":"mode","type":{"name":"i32"}},{"name":"layout","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"radius","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"border","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"stroke","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"fill","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"index","type":{"name":"u32"}}]}},{"at":493,"symbol":"MeshVertex","flags":1,"struct":{"name":"MeshVertex","attributes":[{"name":"export"}],"members":[{"name":"position","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"normal","type":{"name":"vec3","args":[{"name":"f32"}]}},{"name":"color","type":{"name":"vec4","args":[{"name":"f32"}]}},{"name":"uv","type":{"name":"vec2","args":[{"name":"f32"}]}}]}}]},
    "shake": [[0,["PickVertex"]],[74,["SolidVertex"]],[188,["UIVertex"]],[493,["MeshVertex"]]],
    "tree": decompressAST([["Shake",0,69],["Skip",0,7],["Id",15,25],["Id",31,39],["Id",55,60],["Shake",74,183],["Skip",74,81],["Id",89,100],["Id",106,114],["Id",130,135],["Id",151,153],["Id",169,174],["Shake",188,488],["Skip",188,195],["Id",203,211],["Id",217,225],["Id",243,245],["Id",261,270],["Id",286,291],["Id",307,316],["Id",332,338],["Id",350,354],["Id",364,370],["Id",386,392],["Id",408,414],["Id",430,436],["Id",452,456],["Id",474,479],["Shake",493,608],["Skip",493,500],["Id",508,518],["Id",524,532],["Id",548,554],["Id",570,575],["Id",591,593]]),
  };
const libs = {};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const PickVertex = getSymbol("PickVertex");
export const SolidVertex = getSymbol("SolidVertex");
export const UIVertex = getSymbol("UIVertex");
export const MeshVertex = getSymbol("MeshVertex");
/* __WGSL_LOADER_GENERATED */