import { decompressAST } from "../../shader/transform/ast";
import * as m0 from "../use/types";
import * as m1 from "../use/view";
import * as m2 from "../geometry/quad";
const data = {
  "name": "quad",
  "code": "#pragma import {SolidVertex} from '@use-gpu/glsl/use/types'\r\n#pragma import {viewUniforms, worldToClip} from '@use-gpu/glsl/use/view'\r\n#pragma import {getQuadUV} from '@use-gpu/glsl/geometry/quad'\r\n\r\nvec4 getPosition(int);\r\nvec4 getColor(int);\r\nfloat getSize(int);\r\n\r\n#pragma export\r\nSolidVertex getQuadVertex(int vertexIndex, int instanceIndex) {\r\n  vec4 instancePosition = getPosition(instanceIndex);\r\n  vec4 instanceColor = getColor(instanceIndex);\r\n  float instanceSize = getSize(instanceIndex);\r\n\r\n  vec4 position = worldToClip(instancePosition);\r\n\r\n  vec2 uv = getQuadUV(vertexIndex);\r\n  vec2 xy = uv * 2.0 - 1.0;\r\n  \r\n  #ifdef HAS_EDGE_BLEED\r\n  xy = xy * (instanceSize + 0.5) / instanceSize;\r\n  uv = xy * .5 + .5;\r\n  #endif\r\n  \r\n  position.xy += xy * viewUniforms.viewResolution * (instanceSize * position.w);\r\n\r\n  return SolidVertex(\r\n    position,\r\n    instanceColor,\r\n    uv\r\n  );\r\n}",
  "table": {"hash":"3bjq0w2f11","symbols":["getQuadVertex","getPosition","getColor","getSize"],"visibles":["getQuadVertex"],"globals":[],"externals":[{"at":200,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":224,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":245,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}],"modules":[{"at":0,"name":"@use-gpu/glsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]},{"at":0,"name":"@use-gpu/glsl/use/view","symbols":["viewUniforms","worldToClip"],"imports":[{"name":"viewUniforms","imported":"viewUniforms"},{"name":"worldToClip","imported":"worldToClip"}]},{"at":0,"name":"@use-gpu/glsl/geometry/quad","symbols":["getQuadUV"],"imports":[{"name":"getQuadUV","imported":"getQuadUV"}]}],"functions":[{"at":284,"symbols":["getQuadVertex"],"identifiers":["getPosition","getColor","getSize"],"flags":1,"prototype":{"name":"getQuadVertex","type":{"name":"SolidVertex","qualifiers":[]},"parameters":["int","vertexIndex"]}}],"declarations":[{"at":200,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":224,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":245,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}]},
  "shake": [[200,["getPosition","getQuadVertex"]],[224,["getColor","getQuadVertex"]],[245,["getSize","getQuadVertex"]],[284,["getQuadVertex"]]],
  "tree": decompressAST([["Skip",0,60],["Skip",61,134],["Skip",135,197],["Shake",200,222],["Id",205,216],["Shake",224,243],["Id",229,237],["Shake",245,264],["Id",251,258],["Skip",268,283],["Shake",284,893],["Id",284,295],["Id",296,309],["Id",314,325],["Id",331,344],["Id",356,372],["Id",375,386],["Id",387,400],["Id",411,424],["Id",427,435],["Id",436,449],["Id",461,473],["Id",476,483],["Id",484,497],["Id",510,518],["Id",521,532],["Id",533,549],["Id",562,564],["Id",567,576],["Id",577,588],["Id",599,601],["Id",604,606],["Id",652,654],["Id",657,659],["Id",663,675],["Id",685,697],["Id",702,704],["Id",707,709],["Id",738,746],["Id",753,755],["Id",758,770],["Id",789,801],["Id",804,812],["Id",829,840],["Id",847,855],["Id",862,875],["Id",882,884]])
};
const libs = { "@use-gpu/glsl/use/types": m0, "@use-gpu/glsl/use/view": m1, "@use-gpu/glsl/geometry/quad": m2 };
const getSymbol = (entry?: string) => ({ module: data, libs, entry });
export default getSymbol();
export const getQuadVertex = getSymbol("getQuadVertex");
