import {decompressAST} from "../../shader/glsl";
import m0 from "../../glsl/use/types.glsl";
import m1 from "../../glsl/use/view.glsl";
import m2 from "../../glsl/geometry/quad.glsl";
const data = {
    "name": "quad",
    "code": "#pragma import {SolidVertex} from '../../glsl/use/types'\r\n#pragma import {viewUniforms, worldToClip} from '../../glsl/use/view'\r\n#pragma import {getQuadUV} from '../../glsl/geometry/quad'\r\n\r\nvec4 getPosition(int);\r\nvec4 getColor(int);\r\nfloat getSize(int);\r\n\r\n#pragma export\r\nSolidVertex getQuadVertex(int vertexIndex, int instanceIndex) {\r\n  vec4 instancePosition = getPosition(instanceIndex);\r\n  vec4 instanceColor = getColor(instanceIndex);\r\n  float instanceSize = getSize(instanceIndex);\r\n\r\n  vec4 position = worldToClip(instancePosition);\r\n\r\n  vec2 uv = getQuadUV(vertexIndex);\r\n  vec2 xy = uv * 2.0 - 1.0;\r\n  \r\n  #ifdef HAS_EDGE_BLEED\r\n  xy = xy * (instanceSize + 0.5) / instanceSize;\r\n  uv = xy * .5 + .5;\r\n  #endif\r\n  \r\n  position.xy += xy * viewUniforms.viewResolution * (instanceSize * position.w);\r\n\r\n  return SolidVertex(\r\n    position,\r\n    instanceColor,\r\n    uv\r\n  );\r\n}",
    "table": {"hash":"4utaqkcivj","symbols":["getQuadVertex","getPosition","getColor","getSize"],"visibles":["getQuadVertex"],"globals":[],"externals":[{"at":191,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":215,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":236,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}],"modules":[{"at":0,"name":"../../glsl/use/types","symbols":["SolidVertex"],"imports":[{"name":"SolidVertex","imported":"SolidVertex"}]},{"at":0,"name":"../../glsl/use/view","symbols":["viewUniforms","worldToClip"],"imports":[{"name":"viewUniforms","imported":"viewUniforms"},{"name":"worldToClip","imported":"worldToClip"}]},{"at":0,"name":"../../glsl/geometry/quad","symbols":["getQuadUV"],"imports":[{"name":"getQuadUV","imported":"getQuadUV"}]}],"functions":[{"at":275,"symbols":["getQuadVertex"],"identifiers":["getPosition","getColor","getSize"],"flags":1,"prototype":{"name":"getQuadVertex","type":{"name":"SolidVertex","qualifiers":[]},"parameters":["int","vertexIndex"]}}],"declarations":[{"at":191,"symbols":["getPosition"],"identifiers":[],"flags":0,"prototype":{"name":"getPosition","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":215,"symbols":["getColor"],"identifiers":[],"flags":0,"prototype":{"name":"getColor","type":{"name":"vec4","qualifiers":[]},"parameters":["int"]}},{"at":236,"symbols":["getSize"],"identifiers":[],"flags":0,"prototype":{"name":"getSize","type":{"name":"float","qualifiers":[]},"parameters":["int"]}}]},
    "shake": [[191,["getPosition","getQuadVertex"]],[215,["getColor","getQuadVertex"]],[236,["getSize","getQuadVertex"]],[275,["getQuadVertex"]]],
    "tree": decompressAST([["Skip",0,57],["Skip",58,128],["Skip",129,188],["Shake",191,213],["Id",196,207],["Shake",215,234],["Id",220,228],["Shake",236,255],["Id",242,249],["Skip",259,274],["Shake",275,884],["Id",275,286],["Id",287,300],["Id",305,316],["Id",322,335],["Id",347,363],["Id",366,377],["Id",378,391],["Id",402,415],["Id",418,426],["Id",427,440],["Id",452,464],["Id",467,474],["Id",475,488],["Id",501,509],["Id",512,523],["Id",524,540],["Id",553,555],["Id",558,567],["Id",568,579],["Id",590,592],["Id",595,597],["Id",643,645],["Id",648,650],["Id",654,666],["Id",676,688],["Id",693,695],["Id",698,700],["Id",729,737],["Id",744,746],["Id",749,761],["Id",780,792],["Id",795,803],["Id",820,831],["Id",838,846],["Id",853,866],["Id",873,875]]),
  };
const libs = {"../../glsl/use/types": m0, "../../glsl/use/view": m1, "../../glsl/geometry/quad": m2};
const getSymbol = (entry) => ({module: data, libs, entry});
export default getSymbol();
export const getQuadVertex = getSymbol("getQuadVertex");
/* __GLSL_LOADER_GENERATED */